### ISSUE TITLE
Lambda Python Runtimes `<=3.7` no longer supported by CloudFormation

### ISSUE THREAD

**Issue by malachi-constant** [aws-samples/aws-cdk-examples#1003]
### Describe the bug

Lambda Functions with Python Runtimes `<=3.7` are no longer supported by CloudFormation

### Expected Behavior

Successful deployment of examples in repositories.

### Current Behavior

Functions created using the `python3.7` runtime fail with..
```
Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions.
```

### Reproduction Steps

A current failing example:
- [lambda-cron](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/lambda-cron)

### CDK CLI Version

2.131.0

### Node.js Version

v18.16.0

### OS

Mac

### Language

Python

**Comment by kaiz-io** [comment]
Pr merged that fixes this.
