### ISSUE TITLE
Please add a Python example for Fargate Service with EFS

### ISSUE THREAD

**Issue by at21x** [aws-samples/aws-cdk-examples#1027]
### Describe the feature

The TypeScript section features an example of using Fargate with ECS ([link here](https://github.com/aws-samples/aws-cdk-examples/tree/main/typescript/ecs/fargate-service-with-efs)).  I suggest we add the same example in the Python section.  

### Use Case

There are few CDK examples on the web that show Fargate + EFS using Python.  It would be great to have one here.

### Proposed Solution

Create a Python version of this: https://github.com/aws-samples/aws-cdk-examples/tree/main/typescript/ecs/fargate-service-with-efs

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by hareshksaba** [comment]
I may be able to implement this feature request
