### ISSUE TITLE
Add "aws:sample" tag to created example resources

### ISSUE THREAD

**Issue by Robin-Wardle** [aws-samples/aws-cdk-examples#1049]
### Describe the feature

In order to identify these examples within an AWS account, would it be possible to add tags to the resources created by the CDK? 

### Use Case

Although example resources are named appropriately, when working through an example it's not always obvious which resources have been created in the AWS account. Being able to filter by tags - say "aws:sample" or similar - would help identify them for management purposes, particularly useful if costs are being incurred.

I'm particularly interested in the Python code but this feature would apply to all languages.

### Proposed Solution

I don't know enough about CDK tags to be able to suggest an implementation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by kaiz-io** [comment]
It would not work to use CDK tags to identity all resources that were created with CDK application. Tagging coverage is not 100 percent. 

Your best bet to identity all of the resources created by a CDK app and thus the CloudFormation stack is to look at the resources tab in the [CloudFormation console](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-view-stack-data-resources.html). 

CloudFormation also [automatically add stack level tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) which if the resource supports tagging would have that defined as one of it tags.
