### ISSUE TITLE
codepipeline-build-deploy CodeCommit dependency

### ISSUE THREAD

**Issue by jaysonmc** [aws-samples/aws-cdk-examples#1062]
### Describe the bug

For new customers, CodeCommit may not be available. The use of CodeCommit will result in errors for users with new accounts. 

### Expected Behavior

(I have CodeCommit, so no error. New accounts, however, will receive an error).

### Current Behavior

It deployed. But it won't for users of new accounts.

### Reproduction Steps

cdk deploy

### Possible Solution

Move to GitHub

### CDK CLI Version

2.151.0

### Node.js Version

^10.9.1

### OS

amzn2023.x86_64 GNU/Linux

### Language

Typescript

### Language Version

~5.1.6

**Comment by kaiz-io** [comment]
Please don't remove the codecommit one and just add another one for github. You can update the codecommit and link to any public codecommit notices we have. There are still customers that have access that could use the examples for now.
