### ISSUE TITLE
InvalidParameterException

### ISSUE THREAD

**Issue by rakanbakir** [aws-samples/aws-cdk-examples#108]
### What is the problem?
When I tried to deploy the example ecs-load-balanced-service, I got the below error

45/53 | 1:35:19 PM | CREATE_FAILED        | AWS::ECS::Service                         | Ec2Service/Service/Service (Ec2Service398F0E46) The new ARN and resource ID format must be enabled to work with ECS managed tags. Opt in to the new format and try again. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 9a119672-87e6-4b2b-92cb-093563b72d2f)
        new BaseService (/private/var/folders/kp/cxxr8s8d6937_gv2nmkctdkw0000gn/T/jsii-kernel-jONUoW/node_modules/@aws-cdk/aws-ecs/lib/base/base-service.js:39:25)
        \_ new Ec2Service (/private/var/folders/kp/cxxr8s8d6937_gv2nmkctdkw0000gn/T/jsii-kernel-jONUoW/node_modules/@aws-cdk/aws-ecs/lib/ec2/ec2-service.js:40:9)
        \_ new LoadBalancedEc2Service (/private/var/folders/kp/cxxr8s8d6937_gv2nmkctdkw0000gn/T/jsii-kernel-jONUoW/node_modules/@aws-cdk/aws-ecs-patterns/lib/ecs/load-balanced-ecs-service.js:31:24)
        \_ obj._wrapSandboxCode (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6666:49)
        \_ Kernel._wrapSandboxCode (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7131:20)
        \_ Kernel._create (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6666:26)
        \_ Kernel.create (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6419:21)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6191:28)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ KernelHost.processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6233:16)
        \_ KernelHost.run (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:14)
        \_ processRequest (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6137:45)
        \_ promise.then.val (/Users/rakan/github/aws-cdk-examples/python/ecs/ecs-load-balanced-service/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:6218:21)
 46/53 | 1:35:19 PM | CREATE_FAILED        | AWS::EC2::Route                           | MyVpc/PrivateSubnet1/DefaultRoute (MyVpcPrivateSubnet1DefaultRouteA8CDE2FA) Resource creation cancelled

### Reproduction Steps
when the below part execute the problem appear

service = ecs.Ec2Service(
    stack, "Service",
    cluster=cluster,
    task_definition=task_definition
)
### Environment

  - **CDK CLI Version:** 1.6.0
  - **Example:** ecs-load-balanced-service
  - **Example Version:** 
  - **OS:** macOS
  - **Language:** Python

**Comment by rakanbakir** [comment]
it appeared to be not a bug, I had to enable the new ARN and resource ID format.

https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/

**Comment by tom98784** [comment]
Could still be worth documentating that in the example if it's not obvious? (I haven't tried that example myself)

**Comment by rakanbakir** [comment]
yes its should be documented on all ECS examples, who should do that?

**Comment by shivlaks** [comment]
Related issue: aws/aws-cdk#3844

**Comment by akshayamalik** [comment]
Hi , facing the same issue when I am doing deployment with CDK. Any fix or workaround for this ?

**Comment by shivlaks** [comment]
> Hi , facing the same issue when I am doing deployment with CDK. Any fix or workaround for this ?

you'll need to enable the new ARN and resourceId format as described in this [blog post](https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/)

**Comment by akshayamalik** [comment]
Is this

> > Hi , facing the same issue when I am doing deployment with CDK. Any fix or workaround for this ?
> 
> you'll need to enable the new ARN and resourceId format as described in this [blog post](https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/)

Is this something introduced in v >1.4 because I was able to successfully deploy with the same code yesterday and since I have upgraded to 1.6 ,I am facing this problem.

**Comment by shivlaks** [comment]
I do think I saw some changes related to managed tags / propagation that were introduced in the latest release. can you please add your observed behavior to the related issue I linked above?

**Comment by tsykora-verimatrix** [comment]
Even if I opt in for the new ARN format, destroy the ECS stack and deploy again - I still get the error above.
When I disable all tagging in my CDK app the behaviour won't change, I still get the error.
I'm using CDK 1.6.1.

100/101 | 3:27:32 PM | CREATE_FAILED        | AWS::ECS::Service                           | xxxxx/Service (xxxxxx) The new ARN and resource ID format must be enabled to work with ECS managed tags. Opt in to the new format and try again. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: xxxxx)
