### ISSUE TITLE
CREATE_FAILED for AWS::AutoScaling::LaunchConfiguration

### ISSUE THREAD

**Issue by axelson** [aws-samples/aws-cdk-examples#1086]
### Describe the bug

When I run my cdk deploy of https://github.com/aws-samples/aws-cdk-examples/blob/main/python/ecs/ecs-service-with-advanced-alb-config/app.py I get the following error:
```
6:08:15 PM | CREATE_FAILED        | AWS::AutoScaling::LaunchConfiguration         | DefaultAutoScaling...unchConfig8EF01FB2
Resource handler returned message: "The Launch Configuration creation operation is not available in your account. Use launch templates to create configuration templates for your
Auto Scaling groups. (Service: AutoScaling, Status Code: 400, Request ID: 500b4145-4903-4355-81dd-79068d9b10d5)" (RequestToken: 5d5561f2-170a-b103-c699-674ab62b49e0, HandlerError
Code: GeneralServiceException)
```

### Expected Behavior

Instead I expect the cdk deploy to succeed

### Current Behavior

I get the error I posted above

### Reproduction Steps

Follow the readme https://github.com/aws-samples/aws-cdk-examples/tree/main/python and try and run https://github.com/aws-samples/aws-cdk-examples/blob/main/python/ecs/ecs-service-with-advanced-alb-config/app.py

### Possible Solution

I think we need to switch to using a launch template, but I'm not sure how to.

### CDK CLI Version

2.146.0 (build b368c78)

### Node.js Version

v20.18.0

### OS

macos

### Language

Python

### Language Version

Python 3.12.7

**Comment by fanq10** [comment]
You can not call `CreateLaunchConfiguration` with new Amazon EC2 instance types that are released after **December 31, 2022**. In addition, any **new accounts created on or after June 1, 2023 will not** have the option to create new launch configurations through the console. Starting on October 1, 2024, new accounts will not be able to create new launch configurations by using the console, API, CLI, and CloudFormation.

FYI: https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-configurations.html

**Comment by jfan9** [comment]
You can not call `CreateLaunchConfiguration` with new Amazon EC2 instance types that are released after **December 31, 2022**. In addition, any **new accounts created on or after June 1, 2023 will not** have the option to create new launch configurations through the console. Starting on October 1, 2024, new accounts will not be able to create new launch configurations by using the console, API, CLI, and CloudFormation.

FYI: https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-configurations.html

**Comment by axelson** [comment]
@jfan9 I understand that. My issue is that the example posted at https://github.com/aws-samples/aws-cdk-examples/blob/main/python/ecs/ecs-service-with-advanced-alb-config/app.py fails for any accounts created after June 1, 2023. I think the example should be updated so that it works with recently created accounts.
