### ISSUE TITLE
Using AWS from CLI 

### ISSUE THREAD

**Issue by surya-narayanan** [aws-samples/aws-cdk-examples#109]
Hi, I am trying to use CDK deploy from the command line and on some default python resources, from https://github.com/aws-samples/aws-cdk-examples.

When I install the dependencies successfully and try deploying, I get the following messages.

One possible reason is a firewall, but I'm not on one. The message is exactly

"Inaccessible host: cloudformation.oregon.amazonaws.com'. This service may not be available in the Oregon' region."

Any ideas how to fix this or work through it?

**Comment by shivlaks** [comment]
hey @surya-narayanan 

At first glance, it seems like you've incorrectly configured your region in the AWS CLI. can you try running `aws configure` and setting `us-west-2` as your region (which represents Oregon). 

here are the regions supported by[cloudformation](https://docs.aws.amazon.com/general/latest/gr/rande.html#cfn_region), which the CDK CLI will call.

Let me know if deploy runs  for you after that

**Comment by surya-narayanan** [comment]
No, my default region is Oregon

**Comment by shivlaks** [comment]
do cli commands work for you with `Oregon` as the region?

can you point to the example you're trying to use. seems like there's at least a gap where they're missing the `README`. From what I can tell the autoscaling module installs fine for me. Can you provide the the commands you're running and more verbose output ?

[aws-cdk.aws-autoscaling on PIP](https://pypi.org/project/aws-cdk.aws-autoscaling/)

---

To manually create a virtualenv on MacOS and Linux:

```
$ python3 -m venv .env
```

After the init process completes and the virtualenv is created, you can use the following
step to activate your virtualenv.

```
$ source .env/bin/activate
```

If you are a Windows platform, you would activate the virtualenv like this:

```
% .env\Scripts\activate.bat
```

Once the virtualenv is activated, you can install the required dependencies.

```
$ 
```

At this point you can now synthesize the CloudFormation template for this code.

```
$ cdk synth
```
---

**Comment by surya-narayanan** [comment]
These seem to have worked for me. Thank you very much for your help.
