### ISSUE TITLE
Go example for Rekognition Lambda S3 Trigger

### ISSUE THREAD

**Issue by janyaram** [aws-samples/aws-cdk-examples#1096]
### Describe the feature

I would like to extend cdk-examples for Go by adding an example for "Rekognition Lambda S3 Trigger" in Go from the Typescript example. 

### Use Case

There is currently no example for this case in the Go examples. 

### Proposed Solution

I have worked on this example. It follows the pattern from the Typescript example, using Go for both CDK and SDK calls in Lambda. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Go

**Comment by kaiz-io** [comment]
Let me know if you would like to submit a PR on this.

**Comment by mihaws** [comment]
Hi @janyaram, I have a similar example. 
Can you please confirm that the following description follows your needs:
1. cdk stack is buid with Go
2. you have a s3 bucket with an upload listener every time when a file is uploaded a lambda is triggered and Rekognition is usd to analyse the file.
3. The file can be a image 

Is this correct?

**Comment by janyaram** [comment]
Hi @mihaws, I also have an example ready for this. It includes a DynamoDB table with the image and labels for each image following the Typescript example.
