### ISSUE TITLE
Access to CloudFormation layer should be documented for all languages

### ISSUE THREAD

**Issue by foscraig** [aws-samples/aws-cdk-examples#11]
There's lots of TypeScript examples, but I think it's a priority to at least document clearly the "escape hatch" method in all languages as the CDK continues to evolve and might not have all features implemented. For example, I'm trying to access a resource in Java and it's not clear to me how to have the equivalent of `project.node.findChild("Resource")`.

**Comment by Doug-AWS** [comment]
I've added a link to this in https://github.com/awslabs/aws-cdk/issues/1864

**Comment by NGL321** [comment]
The escape-hatch documentation has been updated since this was submitted within the Developer Guide [here](https://docs.aws.amazon.com/cdk/latest/guide/cfn_layer.html).
Closing this issue ftm
