### ISSUE TITLE
(Go) Typo on various README.md's

### ISSUE THREAD

**Issue by dkeithdj** [aws-samples/aws-cdk-examples#1122]
### Describe the bug

typo on various `README` files _toghether_

[httpapi-lambda](https://github.com/aws-samples/aws-cdk-examples/tree/main/go/httpapi-lambda#amazon-api-gateway-http-api-to-aws-lambda)
> This example creates an http api _toghether_ with a simple lambda function returning hello world!

[restapi-lambda](https://github.com/aws-samples/aws-cdk-examples/tree/main/go/restapi-lambda#amazon-api-gateway-rest-api-to-aws-lambda)
> This example creates a rest api _toghether_ with a simple lambda function returning hello world!

[restapi-sqs](https://github.com/aws-samples/aws-cdk-examples/tree/main/go/restapi-sqs#amazon-api-gateway-rest-api-to-amazon-sqs)
> This example creates a rest api _toghether_ with a SQS. By calling the rest api, a message will be forwarded to the SQS.

### Expected Behavior

spelling should be _together_

### Current Behavior

misspelling of _together_

### Reproduction Steps

N/A

### CDK CLI Version

N/A

### Node.js Version

N/A

### OS

N/A

### Language

Go

**Comment by kaiz-io** [comment]
Merged
