### ISSUE TITLE
Environment mapping to AWS Systems Manager Parameter Store

### ISSUE THREAD

**Issue by kaihendry** [aws-samples/aws-cdk-examples#115]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs realistically needs examples of how to setup the environment, ideally with secrets found in AWS ssm. This is typical use case for deploying Docker images on the cloud.

### Proposed Solution

I have been looking for examples on Github search but I've failed: https://github.com/search?q=%27%40aws-cdk%2Faws-elasticloadbalancingv2%27+%27%40aws-cdk%2Faws-ecs%27+environment+%22ssm%22&type=Code

Be great if someone could tell me how it's done. Or is one expected to write the .ts with secrets inlined?

**Comment by kaihendry** [comment]
Keep hitting **SSM Secure reference is not supported in: [AWS::ECS::TaskDefinition/Properties/ContainerDefinitions]** whilst trying to use ssm to fill in secret environment variables.

https://docs.aws.amazon.com/cdk/latest/guide/get_ssm_value.html

**Comment by SoManyHs** [comment]
Pinging @allisaurus on how to reference the secret from within parameter store

**Comment by nickroberts** [comment]
It would be great if somehow we were able to provide the `secrets` property of the ECS container definition to just reference an entry from Secrets Manager (or a Parameter Store JSON entry).

Something like this:
```
const secret = secretsmanager.Secret.fromSecretArn(this, 'Secret', 'my-secret-arn');
const container = taskDefinition.addContainer('Container', {
  // other props removed for brevity
  secrets: ecs.Secret.fromSecretsManager(secret)
});
```

I have no idea if this is possible, or not, but managing multiple secrets or params for each environment is going to get messy.

Another option we are toying with, is encrypting environment based `ts` files with a key / value object. On deploy, decrypt the appropriate one and copy it to the import location, then just spread that in the `environment` property.

```
// custom-environment-variables.ts
export const customEnvironmentVariabls = {
  SOME_SECRET: 'Some secret value
}
```
```
// build script would decrypt and copy the file
// ENV=dev, etc...
decrypt custom-environment-variables/${ENV}.ts
cp custom-environment-variables/${ENV}.ts lib/custom-environment-variables.ts
```
```
import { customEnvironmentVariables } from './custom-environment-variables';
// code removed for brevity
const container = taskDefinition.addContainer('Container', {
  // other props removed for brevity
  environment: {
    SOME_VAR: 'Some Value',
    ...customEnvironmentVariables
  }
});
```

This would allow us to use defaults, then for another environment, override the default.
