### ISSUE TITLE
cdk.json

### ISSUE THREAD

**Issue by kaihendry** [aws-samples/aws-cdk-examples#116]
What generates the cdk.json that `--app is required either in command-line, in cdk.json or in ~/.cdk.json` demands? I end up just creating the `cdk.json` file like so manually: `{ "app": "node index" }`

**Comment by rhboyd** [comment]
it's usually generated when you run [`cdk init sample-app`](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/init-templates/sample-app/typescript/cdk.template.json) or [`cdk init app`](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/init-templates/app/typescript/cdk.template.json).

if you've found examples in the aws-cdk-examples repo that don't have the required configuration to synth/deploy out of the box, feel free to open issues for them.
