### ISSUE TITLE
Cdk python document mixed with Node.js code example

### ISSUE THREAD

**Issue by zanhsieh** [aws-samples/aws-cdk-examples#119]
### What is the problem?
Python document mixed with node.js code. For example, construct a new Vpc:

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2/Vpc.html

```
import { SubnetType, Vpc } from '@aws-cdk/aws-ec2'

const vpc = new Vpc(this, 'TheVPC', {
   cidr: "10.0.0.0/16"
})

// Iterate the private subnets
const selection = vpc.selectSubnets({
   subnetType: SubnetType.PRIVATE
});

for (const subnet of selection.subnets) {
   // ...
}
```
This is node.js / typescript code, not python code.

Advanced Subnet Configuration
Connection Peers
....

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ec2.README.html

Amazon ECR Construct Library

https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecr.README.html

### Reproduction Steps
Simple. For Vpc, in CLI do this:

```
$ python
>>> from aws_cdk.aws_ec2 import Vpc
>>> help(Vpc)
```

### Environment

  - **CDK CLI Version:1.8.0 (build 5244f97)** 
  - **OS:OSX Mojave** 
  - **Language:Python**

**Comment by tom98784** [comment]
Unfortunately, this happens rather a lot in the Python documentation - I've also seen variables written camel-case when they're actually snake case in Python.

This is just the samples repo though, so this is probably best raised on the CDK repo unless there are examples of it in the documentation with the examples here.
[https://github.com/aws/aws-cdk](https://github.com/aws/aws-cdk)

**Comment by zanhsieh** [comment]
New issue in aws-cdk created. 
https://github.com/aws-samples/aws-cdk-examples/issues/119
