### ISSUE TITLE
Move example list to sub-directories

### ISSUE THREAD

**Issue by rhboyd** [aws-samples/aws-cdk-examples#123]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description
Can we break up the list of examples in the README.md into separate README.mds in each language's sub-directory, it leads to quite a few merge conflicts with the current design. The main README.md would then just contain pointers to each language's specific list of examples.

### Proposed Solution
1 README.md -> 5 README.mds (one in each language directory

### Environment
Github

**Comment by ryparker** [comment]
Done. Seems like we forgot to close this.
