### ISSUE TITLE
Automate keeping package.json in sync with latest CDK version

### ISSUE THREAD

**Issue by SoManyHs** [aws-samples/aws-cdk-examples#13]
Any updates to CDK construct libs require manual update of package.json in every example. We should probably try to figure out a better way to do this.

**Comment by simalexan** [comment]
They don't, they are automatically set to the highest version:
Example: `"@aws-cdk/cdk": "*"`
And thats set within tests too, the tests will fail if a version is set.

**Comment by simalexan** [comment]
@SoManyHs I think this one is solved already, as per comment above. 

@rix0rrr what do you think?

**Comment by rix0rrr** [comment]
Yep, you are right.

**Comment by simalexan** [comment]
@rix0rrr thank you for your quick review!
