### ISSUE TITLE
ECS Fargate Load Balanced Service created via python example does not allow incoming traffic

### ISSUE THREAD

**Issue by heiwad** [aws-samples/aws-cdk-examples#131]
### What is the problem?
When deploying  python/ecs/fargate-load-balanced-service/ the resulting application is not reachable via the load balancer URL.

The security group for the fargate task does not have an inbound rule allowing traffic on port 80. Manually adding the rule post deployment fixes the application.

### Verbose Log
the result of cdk synth shows that the generated YAML does not include any rules for security group ingress. 

FargateServiceSecurityGroup262B61DD:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Bonjour/FargateService/Service/SecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"

### Environment

  - **CDK CLI Version:** 1.9.0 (build 30f158a)
  - **Example:** ECS Fargate Load Balanced Service
  - **Example Version:** Latest commit e7b755c
  - **OS:** Ubuntu
  - **Language:** Python

**Comment by davidsteed** [comment]
Not just python. This does not work

**Comment by davidsteed** [comment]
Could you put your solution here.  Did you create the security group using cdk or edit the generated cloudformation

**Comment by heiwad** [comment]
I was able to solve by adding the following line of code after line 30

fargate_service.service.connections.allow_from_any_ipv4(ec2.Port.tcp(80),'Allow HTTP access to the website')

**Comment by davidsteed** [comment]
I get "Property 'allow_from_any_ipv4' does not exist on type
'Connections'."  when I try that

**Comment by davidsteed** [comment]
Ah! they have changed it to allowFromAnyIpv4().  thank you very much - I
spent ages trying to figure that out

**Comment by SomayaB** [comment]
Closing since a solution seems to have been found. Feel free to reopen if that's not the case.
