### ISSUE TITLE
Use NODEJS_10_X for Lambda Runtime as NODEJS_8_10 is EoL on 31 Dec 2019

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-cdk-examples#132]
### What is the problem?
* NODEJS_8_10 is EoL on 31 Dec 2019 https://endoflife.date/nodejs
* It's advisable to use NODEJS_10_X in example code

### Reproduction Steps
* Follow readme in [api-cors-lambda-crud-dynamodb](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/api-cors-lambda-crud-dynamodb)
* Notice that lambda is deployed on `Node.js 8.10`

### Verbose Log
N/A

### Environment
N/A

**Comment by rhboyd** [comment]
EOL from the Node.js Foundation doesn't mean EOL from Lambda support. historically, the Node versions have been supported by Lambda for some time after they are EOL by Node.js
