### ISSUE TITLE
Static Site: GET /subdirectory should serve /subdirectory/index.html

### ISSUE THREAD

**Issue by btakita** [aws-samples/aws-cdk-examples#152]
It does not seem like subdirectory index files are served. Instead a GET /subdirectory responds with a 403

**Comment by NGL321** [comment]
Hey @btakita,

Sorry for the delay, this was listed as a feature request (when it seems like a potential bug to me) and got passed over. A cursory look and I was unable to reproduce this.

A 403 Error strikes me as a potential permissions issue from your AWS configuration. Could you give me more reproduction steps? In particular, this example does not run out of the box and requires more information from the user.

**Comment by btakita** [comment]
It looks like the standard way to do the rewrite is to use lambda@edge. Problem with lambda@edge is that it's difficult to remove the functions once created.

This post uses CloudWatch. I have not tried it but seems easier to manage than lambda@edge.

https://someguyontheinter.net/blog/serving-index-pages-from-a-non-root-location-via-cloudfront/

**Comment by fibo** [comment]
you can also do that creating a "subdirectory" file containing HTML and adding the `text/html` content type on S3

of course with this solution you cannot have other files or routes inside the "subdirectory"

a simpler solution could be to have a "subdirectory.html" path

If I am not wrong, having the URL "subdirectory" serving a "subdirectory/index.html" is not a specification, it comes from Apache rewrites or similar. It is a feature we are used to, not something that "should" be.
