### ISSUE TITLE
Example VPC with SSM Endpoints

### ISSUE THREAD

**Issue by chriswessells** [aws-samples/aws-cdk-examples#163]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Example of a VPC with the endpoints necessary for AWS Systems Manager Agent to communicate without using a IGW or NAT Gateway (private subnets that do not have access to the Internet).

### Proposed Solution

I have working CDK code I use when mocking up environments. I would add the Typescript to the aws-cdk-examples in the expected format.

### Environment

  - **CDK CLI Version:** most current
  - **Example:** vpc-ssm-endpoints
  - **Example Version:** 
  - **OS:** OSX Mojave, although it should work across all OS
  - **Language:** TypeScript

**Comment by josjaf** [comment]
I have this in Python if anybody is interested

**Comment by khbvirus** [comment]
> I have this in Python if anybody is interested

@josjaf interested in the python solution for this.

**Comment by josjaf** [comment]
I'll post it on github for you tomorrow

**Comment by josjaf** [comment]
https://github.com/josjaf/aws-cdk-examples/tree/feature/vpc/python/vpc

**Comment by kaizio** [comment]
We have an example using SSM endpoints. https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ec2-ssm-local-zone/example-localzone-stack.ts
