### ISSUE TITLE
Statement of Purpose for the examples repository

### ISSUE THREAD

**Issue by rhboyd** [aws-samples/aws-cdk-examples#177]
## :question: Guidance Question
The aws-cdk-examples repository should include a statement of purpose for the repository. It feels like its somewhere between a teaching resource with many examples and a collection of patterns. I would propose that we say production-ready examples with best-practices baked-in belong in the patterns section of @aws-cdk and this repository is used to hold demonstration examples that aren't expected to have extensive feature support or specific best-practices.

I've seen several examples of people asking for production-grade feature requests of the examples in this repository, citing the need for production readiness, as well as people opening up ALB ports to the whole internet. Trying to accomplish both goals in the same repository is going to cause confusion and ultimately create a bad experience for our users.

**Comment by nija-at** [comment]
Apps under the CDK examples repos showcase non-trivial use cases of the CDK or integrations across AWS services. They will not carry a full blown production application unless the application is very simple.

The examples in the repository will show examples and recommendations on how to use the CDK, but will not carry any opinions or recommendations around project structure, code organization, managing configuration and environments.

**Comment by ryparker** [comment]
Can we close this?

**Comment by richardhboyd** [comment]
sure
