### ISSUE TITLE
Python Fargate Service with load balancing doesn't open required security group ports

### ISSUE THREAD

**Issue by dchristian3188** [aws-samples/aws-cdk-examples#190]
### What is the problem?
When running the [Python Fargate load balanced service](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/fargate-load-balanced-service) the required ports are not open on the Fargate service security group. For the service to work correctly, the security group needs to allow port 80 inbound from the VPC subnets.

### Environment

  - **CDK CLI Version:** 1.18.0 (build bc924bc)
  - **Example:** [Python Fargate load balanced service](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/fargate-load-balanced-service)
  - **Example Version:** current
  - **OS:** all
  - **Language:** Python

**Comment by SomayaB** [comment]
Hi @dchristian3188, thanks for reporting these bugs and opening PRs, much appreciated! 👍
