### ISSUE TITLE
Certain resources should have a from_json method

### ISSUE THREAD

**Issue by mannickutd** [aws-samples/aws-cdk-examples#194]
### General Information
For the class https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iam/PolicyDocument.html#aws_cdk.aws_iam.PolicyDocument
There is a way to generate the json for a policy document.
What I am looking for is a way to go the other way.
Eg. I have the json for a policy
{
  "Version": "2012-10-17",
  "Statement": [{"Effect": "Allow", "Action": "*:*", "Resource":"*"}]
}
I want to create the PolicyDocument object from the json.
I find that I am writing boilerplate code for converting from configuration files (yaml) to cdk Classes. Is there already a library out there that does this for me?
* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Proposed Solution
A suitable yaml or json converter for cdk classes where this makes sense. It would also be good to inject string or key value replacements inside the yaml or json configuration files.
### Environment
I am looking at the current 1.18.0 version of the library.

**Comment by rhboyd** [comment]
I would submit this issue to the aws-cdk repository. This repository is just for code examples using CDK.
