### ISSUE TITLE
How to create a conditional Glue trigger with predicates is not clearly documented. A sample would help. 

### ISSUE THREAD

**Issue by SomayaB** [aws-samples/aws-cdk-examples#205]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I am struggling with creating a Glue workflow in my Python cdk script.
Specifically I want to create a trigger that is waiting for a set of Glue jobs to successfully complete before performing its action

_Originally posted by @ksadeghi in https://github.com/aws/aws-cdk/issues/5251#issuecomment-559676287_
### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by NGL321** [comment]
Hi @ksadeghi,

Is this still something you are interested in? This could potentially be added to a Stepfunctions example if so.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.
