### ISSUE TITLE
How do you use APIGatewayV2 HTTP API with CDK to save 70% cost on API?

### ISSUE THREAD

**Issue by bionicles** [aws-samples/aws-cdk-examples#212]
### Description
We want to use the new HTTP API with AWS Lambda because it’s simpler, lower latency, and faster, but it’s not documented

### Proposed Solution
A construct to deploy a simple lambda with http api (node js)

**Comment by bionicles** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html

**Comment by bionicles** [comment]
announced a few weeks ago: 
https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/

**Comment by bionicles** [comment]
APIGatewayV2 was just split into its own package today

https://github.com/aws/aws-cdk/commit/d58667e473c1e07ac8f2f073b3a541569a014e01

**Comment by rhboyd** [comment]
Because this is an experimental module, you would most likely need to use the underlying L1 Constructs to build an API Gateway HTTP API. Given that the feature itself is still in Beta preview and may experience breaking changes, I would doubt many people would be willing to do the work to build solid Construct on top of it until it goes GA.

**Comment by NGL321** [comment]
Hey @bionicles,
Richard is correct in that a specific L1 construct implementation doesnt make a lot of sense for an example for the moment.
That said, I think once there is an L2 for ApiGatewayV2, this is a perfect example to add.

With that in mind, Im going to delay this for execution once the [L2 is completed](https://github.com/aws/aws-cdk/issues/2872)

**Comment by aang7** [comment]
Yet there is not an example? :cry:

**Comment by iamgauravj** [comment]
can someone provide example for "custom lambda authorizer with http api"

**Comment by kaiz-io** [comment]
CDK API Docs has example https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_apigatewayv2-readme.html
