### ISSUE TITLE
How do you deploy aurora serverless postgres with CDK?

### ISSUE THREAD

**Issue by bionicles** [aws-samples/aws-cdk-examples#218]
### Description
I want to use the Aurora **Serverless** Postgres database with Hasura container in Fargate or a lambda on Nodejs but there is no clear explicit example of the database and the reference docs are not searchable. 

### Proposed Solution
Would it please be possible to add a simple stack to deploy aurora serverless postgres with CDK?

**Comment by richardhboyd** [comment]
The [RDS CDK docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-rds-readme.html#starting-a-clustered-database) show how to create an Amazon Aurora Database.

**Comment by bionicles** [comment]
Thank you @richardhboyd

**Comment by netroy** [comment]
@bionicles here is the CDK issue to follow https://github.com/aws/aws-cdk/issues/929
and, here is an unofficial example that uses `engineMode` in a custom construct https://github.com/ysku/aurora-serverless-example

IMHO, until official support for Aurora-Serverless lands in CDK, it probably doesn't make much sense to add a temporary (& hacky) example here.

**Comment by bionicles** [comment]
sounds good @netroy how do you add the official support to cdk?

**Comment by richardhboyd** [comment]
someone would have to add a L2 Construct that creates an aurora serverless database

**Comment by NGL321** [comment]
Since it seems this would require a [major addition](https://github.com/aws/aws-cdk/issues/929) to the CDK repo to be officially supported, I am going to close this issue for now.

If I misunderstand the scope and this is achievable now, or once the feature is completed in the main repo, please feel free to reopen the issue!

😸
