### ISSUE TITLE
Please add a serverless graph stack

### ISSUE THREAD

**Issue by bionicles** [aws-samples/aws-cdk-examples#222]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description
I think a full stack React + CDK + Neptune Serverless example would be valuable for many startups because graphs enable a whole range of new queries that are mostly impossible in SQL. Serverless would help to focus on customers instead of servers and capacity guessing

### Proposed Solution
Host a react front end with S3, Cloudfront, and Route53. (Easy)

Make a serverless graph API with API Gateway v2 HTTP API to a NodeJS Lambda function which handles fine grained access control and graph db CRUD (Need support for v2 API Gateway constructs)

Add a Serverless option for Neptune (not sure how hard this is) and optionally support Cypher out of the box (Gremlin is fine for me but I’d rather use Cypher)

### Environment

  - **OS:** ALL
  - **Language:** CODE NODE

### Other information
It’s a big project. Would require help from the Neptune team to enable Serverless mode.

Please help @eladb !

**Comment by richardhboyd** [comment]
Currently, Neptune doesn't have a serverless capability so this feature would be blocked until such a feature is developed by the Neptune service team.

**Comment by NGL321** [comment]
@bionicles 
This seems like an excellent idea! If you think it would be valuable this could be developed with a substitute for Neptune, or developed with server-based Neptune and adapted for serverless Neptune later.

Let me know what you think!

😸

**Comment by namedgraph** [comment]
Any progress on this?

**Comment by NGL321** [comment]
@namedgraph I don't think anyone is presently working on this (contributions are super appreciated!). 
Neptune still doesn't have serverless capability, so it remains blocked on that front.

**Comment by bionicles** [comment]
Alas, there are 50 billion graph databases but none serverless

**Comment by dekoza** [comment]
Any example of Neptune CDK config set to interact with other services like S3 would be great.

**Comment by kaiz-io** [comment]
Closing for staleness. Comment/reopen if still interested.
