### ISSUE TITLE
At least two subnets in two different Availability Zones must be specified

### ISSUE THREAD

**Issue by Antoine-C** [aws-samples/aws-cdk-examples#226]
### What is the problem?
I'm trying to build the _application-load-balancer_  exemple (typescript) but unfortunately it fails when trying to create the Elastic Load Balancer due to missing subnets settings.

### Reproduction Steps
Just git clone the _application-load-balancer_ exemple and run cdk deploy.

### Verbose Log
```
 18/23 | 22:38:43 | CREATE_FAILED        | AWS::ElasticLoadBalancingV2::LoadBalancer | LB (LB8A12904C) At least two subnets in two different Availability Zones must be specified (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: ValidationError; Request ID: 4932b66c-04c3-451e-b139-50e38043b6e5)
```

### Environment

  - **CDK CLI Version:** 1.20.0 (build 021c521)
  - **Example:** application-load-balancer
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by maskerade** [comment]
Unable to replicate this today with CDK version 1.48.0 (build 6080fa8)

**Comment by NGL321** [comment]
@maskerade thanks for the check!

This has been fixed. Closing out the issue

😸 😷
