### ISSUE TITLE
Example `typescript/ecs/fargate-service-with-local-image` does not produce a working service

### ISSUE THREAD

**Issue by rschmitt** [aws-samples/aws-cdk-examples#227]
### What is the problem?
The `fargate-service-with-local-image` deploys successfully, but the service cannot be contacted. Looking in the ELB console, it says that "none of these Availability Zones contains a healthy target." The registered targets are either in the "initial" or "draining" status.

### Reproduction Steps
Apply the `README.md` instructions to the `typescript/ecs/fargate-service-with-local-image` example. I used `AWS_REGION=us-west-2`.

### Verbose Log
Let me know if you need this.

### Environment

  - **CDK CLI Version:** 1.20.0 (build 021c521)
  - **Example:** fargate-service-with-local-image
  - **Example Version:** ee91f30f062ba2659977a9822e569efc34e0593a
  - **OS:** macOS Mojave 10.14.6
  - **Language:** TypeScript

**Comment by BinaryShrub** [comment]
All of the fargate examples are having this issue for me. Is there any update on this?

**Comment by iamhopaul123** [comment]
Hi @rschmitt, it is because it is using NLB, which does not come with a security group that opens all traffic. For security concern you need to configure manually: https://github.com/aws-samples/aws-cdk-examples/issues/131

**Comment by rschmitt** [comment]
@iamhopaul123 This explanation doesn't make any sense to me. I created an EC2 instance inside the same security group as the Fargate service, and I was still unable to ping the service.

**Comment by iamhopaul123** [comment]
> @iamhopaul123 This explanation doesn't make any sense to me. I created an EC2 instance inside the same security group as the Fargate service, and I was still unable to ping the service.

Yeah, I agree. We'll fix that.
