### ISSUE TITLE
ECS cluster example build fails with latest CDK

### ISSUE THREAD

**Issue by eladb** [aws-samples/aws-cdk-examples#23]
The [ECS cluster](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ecs/cluster) example fails when built against the latest CDK with the following error:

```
To set 'associatePublicIpAddress: true' you must select Public subnets (vpcSubnets: { subnetType: SubnetType.Public })
```

**Comment by SoManyHs** [comment]
Should be fixed by https://github.com/aws-samples/aws-cdk-examples/pull/26
