### ISSUE TITLE
Some ECS Examples dont have READMEs

### ISSUE THREAD

**Issue by NGL321** [aws-samples/aws-cdk-examples#236]
### What is the problem?

The following examples dont contain README files to describe purposed:

[TS ECS w/Logging](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/ecs-service-with-logging/)
[Python Fargate w/Autoscaling](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/fargate-service-with-autoscaling/)

**Comment by pkandasamy91** [comment]
@NGL321 not really sure what the expectation is here? None of the examples in the ECS repo have readmes.
