### ISSUE TITLE
Need examples of importing CFN exports for use in declaring service properties

### ISSUE THREAD

**Issue by geof2001** [aws-samples/aws-cdk-examples#237]
### The Question

I'm looking for a way to use string/array exports from existing CF stacks like CF does it already. 
 For example we have an ECS cluster exported from an existing stack which is just the Name string for the cluster.  However I can't seem to use that when trying to define a ecs.Ec2Service. 
 The cluster property here says it requires a type of ICluster which the string doesn't satisfy.  With native CFN this works find to just do the Fn::ImportValue of the string.  Some of the examples I have seen have been to declare a function that does a fromLookup but then you need to supply required attributes of the cluster like clustername, vpc, security groups.  This is way too complex so I think this is the wrong approach.  Can someone help me out with the right way to go about this without writing many lines of code just to use an export from an existing stack as value in CDK?[2]!

[2]: http://xyproblem.info

### Environment

  - **CDK CLI Version:** 1.21.1 (build 842cc5f)
  - **Example:** Name of the example in question
  - **Example Version:** Version of the example in question
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by richardhboyd** [comment]
You would do something like 
```typescript
const myValue = new FnImportValue("myExportName")
```

[Here](https://github.com/aws/aws-cdk/blob/e441d8bf5d501905e9c1448d550195268c61f4cc/packages/%40aws-cdk/core/lib/cfn-fn.ts#L388-L401) is where the class is defined in CDK

**Comment by NGL321** [comment]
@geof2001,

Did Richard's answer above help you with this? This seems like too specific of a use-case to have its own example (I could be wrong). If you disagree or the above didnt help, please leave a comment and I will update.
