### ISSUE TITLE
Error: Cannot retrieve value from context provider hosted-zone since account/region are not specified at the stack leve

### ISSUE THREAD

**Issue by kbroughton** [aws-samples/aws-cdk-examples#238]
## :bug: Bug Report
Need more instructions in readme.
First, you need to import modules via npm or yarn.
Then, need to get region and account into context.

### What is the problem?
`cdk deploy` causes errors.

### Reproduction Steps
aws-cdk-examples/typescript/static-site> cdk synth -c domain=x.com -c subdomain=y
l. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)

I've defined the CDK_ variables in the shell.

### Verbose Log
aws-cdk-examples/typescript/static-site/node_modules/@aws-cdk/core/lib/context-provider.js:41
            throw new Error(`Cannot retrieve value from context provider ${options.provider} since account/region ` +
            ^

Error: Cannot retrieve value from context provider hosted-zone since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)
    at Function.getValue (~/aws-cdk-examples/typescript/static-site/node_modules/@aws-cdk/core/lib/context-provider.js:41:19)
    at Function.fromLookup (~/aws-cdk-examples/typescript/static-site/node_modules/@aws-cdk/aws-route53/lib/hosted-zone.js:71:49)
    at new StaticSite (~/aws-cdk-examples/typescript/static-site/static-site.js:21:41)
    at new MyStaticSiteStack (~/aws-cdk-examples/typescript/static-site/index.js:20:9)
    at Object.<anonymous> (~/aws-cdk-examples/typescript/static-site/index.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
Subprocess exited with error 1

### Environment

  - **CDK CLI Version:** 1.22.0 (build 309ac1b)
  - **Example:** typescript/static-site
  - **Example Version:** 1.0.0
  - **OS:** OSX Mojave
  - **Language:** TypeScript

**Comment by iamhopaul123** [comment]
@kbroughton I think it is because you don't have the default profile in your aws config file. Can you run `aws configure` to see if it fixes the problem?

**Comment by kbroughton** [comment]
I do have ~/.aws/config and ~/.aws/credentials [default] blocks defined.

e.g. for config.
[default]
region = us-east-1
output = json

I use the keys regularly. I also tried explicitly setting CDK_ vars on the CLI - no luck. 
aws configure does not set a "default account" either.

**Comment by iamhopaul123** [comment]
Here's the [guidance](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) that is relevant to your issue. Does this help solve your issue?

**Comment by StraightOuttaCrompton** [comment]
I also experienced this issue receiving the message 

> Cannot retrieve value from context provider hosted-zone since account/region are not specified at the stack level. Either configure "env" with explicit account and region when you define your stack, or use the environment variables "CDK_DEFAULT_ACCOUNT" and "CDK_DEFAULT_REGION" to inherit environment information from the CLI (not recommended for production stacks)

I was puzzled when setting the environment variables and getting the same error. It took me a while to figure out I have to do the following 

```ts
new MyDevStack(app, 'dev', { 
  env: { 
    account: process.env.CDK_DEFAULT_ACCOUNT, 
    region: process.env.CDK_DEFAULT_REGION 
}});
```

as outlined in the [guidance](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) provided by @iamhopaul123

**Comment by SomayaB** [comment]
Thanks @iamhopaul123 and @StraightOuttaCrompton! @kbroughton does that solve your issue?

**Comment by SomayaB** [comment]
Closing this issue since a solution seems to have been found. Feel free to reopen.

**Comment by amilnayar92** [comment]
@iamhopaul123 I am still facing this issue even after providing the `env`. This error only happens when i use nested stacks. For normal stack it works fine! Using cdk 1.38.0

**Comment by iamhopaul123** [comment]
@amilnayar92 can you open another issue and provide more details about the issue you have?

**Comment by amilnayar92** [comment]
@iamhopaul123  Two issues open with same errors: https://github.com/aws/aws-cdk/issues/5547 and https://github.com/aws/aws-cdk/issues/4651

**Comment by iamhopaul123** [comment]
@amilnayar92 oh seems like it is a route53 problem. `HostedZone.fromLookup` just doesn't work for nested stack. We probably are not able to solve it on our end but glad to be informed about the existence of this issue!

**Comment by evayde** [comment]
@iamhopaul123 You've saved me a quintillion hours of debugging. Thanks.

**Comment by dillonharlessCORE** [comment]
> @amilnayar92 oh seems like it is a route53 problem. `HostedZone.fromLookup` just doesn't work for nested stack. We probably are not able to solve it on our end but glad to be informed about the existence of this issue!

Really? I feel like this throws a pretty big wrench in the ideal that you can "keep your infrastructure and app code in the same repository", per the AWS CDK best practices document on AWS's website...

**Comment by rondamstra** [comment]
import * as cdk from 'aws-cdk-lib';
import { CodePipeline, CodePipelineSource, ShellStep } from 'aws-cdk-lib/pipelines';
import { Construct } from 'constructs';
import { PipelineStage } from './PipelineStage';
import { Fn } from 'aws-cdk-lib';

export class CdkStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const pipeline = new CodePipeline(this, 'RonDamstraPipeline', {
      pipelineName: 'RonDamstraPipeline',
      synth: new ShellStep('Synth', {
        input: CodePipelineSource.gitHub('rondamstra/rondamstra.nl.cdk', 'main'),
        commands: [
          'npm ci',
          'npx cdk synth'
        ],
        primaryOutputDirectory: 'cdk.out',
      })
    });

    const uiStage = new PipelineStage(this, 'UiStage', {
      stageName: 'UiStage'
    });
    pipeline.addStage(uiStage);

    const frontendBucketName = Fn.importValue('FrontendBucketName-UiStage');

    const frontendStage = pipeline.addStage(new PipelineStage(this, 'FrontendStage', {
      stageName: 'DeployFrontend'
    }));

    frontendStage.addPre(new ShellStep('BuildReactApp', {
      input: CodePipelineSource.gitHub('rondamstra/rondamstra.nl.frontend', 'main'),
      commands: [
        'npm ci',
        'npm run build',
      ]
    }));

    frontendStage.addPost(new ShellStep('DeployToS3', {
      commands: [
        `aws s3 sync build/ s3://${frontendBucketName} --delete`
      ],
    }));

  }
}
