### ISSUE TITLE
Unused code in MyWidgetServiceStack

### ISSUE THREAD

**Issue by davidmoten** [aws-samples/aws-cdk-examples#239]
https://github.com/aws-samples/aws-cdk-examples/blob/0612ac04cbfe46831ed4f077b38194d649a8fdea/java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceStack.java#L38-L42

The above variable `restApiRole` is not used anywhere. What's the story?

**Comment by rhboyd** [comment]
It’s used here

https://github.com/aws-samples/aws-cdk-examples/blob/0612ac04cbfe46831ed4f077b38194d649a8fdea/java/my-widget-service/src/main/java/software/amazon/awscdk/examples/MyWidgetServiceStack.java#L41

**Comment by rhboyd** [comment]
My bad. I misread your email and thought you said the variable above RestAPI Role. I assume that someone changed the example from an APIGW service integration to a Lambda Integration and didn’t remove the older parts in the Python or TS examples. When it was translated to Java, those artifacts remained.

**Comment by rhboyd** [comment]
They probably tried to copy this example, then gave up.

https://github.com/aws-samples/aws-cdk-examples/blob/master/python/my-widget-service/my_widget_service/my_widget_service_stack.py#L23

**Comment by davidmoten** [comment]
Given that this project is put forward as a official examples, are the examples tested (or just translated and thrown in)?

**Comment by NGL321** [comment]
@davidmoten,

Thank you for the catch. This looks like it warrants a more thorough sweep of the Java examples to ensure they are of an acceptable quality.

> Given that this project is put forward as a official examples, are the examples tested (or just translated and thrown in)?

These examples are tested via a CI test suite, but it seems linting is not presently run on the Java examples.

**Comment by kaiz-io** [comment]
Was fixed
