### ISSUE TITLE
Cognito user pool + APIGW + Lambdas

### ISSUE THREAD

**Issue by NGL321** [aws-samples/aws-cdk-examples#244]
### General Information
_On behalf of @ximarin. Original issue [here](https://github.com/aws-samples/aws-cdk-intro-workshop/issues/103)_

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Is it possible to get a step by step example for how to set up an APIGW so it uses specific Cognito user pools for specific URLs?

Similar to [this question on stackoverflow](https://stackoverflow.com/questions/59489587/aws-cdk-tie-cognito-user-pool-to-api-gateway).

### Proposed Solution

The idea is to have a working set of Cognito user pools.
These should then be used as Authorizers for a set of API GW Rest APIs that trigger lambdas.
The example should explain how to create the authorizers properly.
The example should also explain how to make use of the tokens within lambda.

**Comment by campionfellin** [comment]
I can give this an attempt! Assigning to myself.

**Comment by NGL321** [comment]
Should have been closed by #252
