### ISSUE TITLE
Need some examples for adding AWS SSM Patch Baseline

### ISSUE THREAD

**Issue by arunssasidhar** [aws-samples/aws-cdk-examples#248]
Hello,

I am using AWS CDK with Python.
 I am trying to add AWS SSM Patch Baseline using following code

`ssm_patch_baseline = ssm.CfnPatchBaseline(
            self, 'AmazonLinux2DemoPatchBaseline',
            name='AmazonLinux2DemoPatchBaseline',
            operating_system='WINDOWS',
            approval_rules={'PatchRules': [{'PatchFilterGroup': {'PatchFilters': [{ 'Key': 'PRODUCT', 'Values': ['WindowsServer2019']}, { 'Key': 'SEVERITY', 'Values': ['Critical']}, {'Key' : 'CLASSIFICATION', 'Values' : ['CriticalUpdates']}]}, 'ApproveAfterDays': 5}]},           
            description='Baseline containing all updates approved for Amazon Linux2 instances'
        )`

But in the Cloudformation output, the "ApprovalRules" is showing as NULL as seen below -
`$ cdk synth
Resources:
  AmazonLinux2DemoPatchBaseline:
    Type: AWS::SSM::PatchBaseline
    Properties:
      Name: AmazonLinux2DemoPatchBaseline
      ApprovalRules: {}
      Description: Baseline containing all updates approved for Amazon Linux2 instances
      OperatingSystem: WINDOWS
    Metadata:
      aws:cdk:path: cdk-test/AmazonLinux2DemoPatchBaseline
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.25.0,@aws-cdk/aws-cloudwatch=1.23.0,@aws-cdk/aws-ec2=1.23.0,@aws-cdk/aws-iam=1.23.0,@aws-cdk/aws-kms=1.23.0,@aws-cdk/aws-ssm=1.23.0,@aws-cdk/core=1.23.0,@aws-cdk/cx-api=1.23.0,@aws-cdk/region-info=1.23.0,jsii-runtime=Python/3.6.8`

Could you please provide some insights into this issue?
It would be great if you could provide some example Python code for AWS SSM Patch Manger.

Thanks,
Arun Sasidharan

**Comment by MrArnoldPalmer** [comment]
hey @arunssasidhar, there is an issue with the python docs displaying nested type definitions. You need to pass this in like so
```python
ssm.CfnPathBaseline(self, 'Id', approval_rules=CfnPathBaseline.RuleGroupProperty(patch_rules=[CfnPatchBaseline.RuleProperty(patch_filter_group=CfnPatchBaseline.PatchFilterGroupProperty(patch_filters=[cfnPatchBaseline.PatchFilterProperty(.........
```
Best way to trace these types currently is to look at the language generic API docs. All of the types have their python names at the top of the page and all of the argument names for type initializers are `snake_case`. [CfnPatchBaseline.RuleProperty](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ssm.CfnPatchBaseline.RuleProperty.html) for references.

You can also look at the source code of the python modules but the former is probably easier.

Here is an example that demonstrates [nested property initialization in an L1 resource](https://github.com/aws-samples/aws-cdk-examples/blob/master/python/appsync-graphql-dynamodb/app_sync_cdk/app_sync_cdk_stack.py#L96)

[Relevant JSII issue](https://github.com/aws/jsii/issues/474)
