### ISSUE TITLE
Need some examples for adding Tags to EC2 instance

### ISSUE THREAD

**Issue by arunssasidhar** [aws-samples/aws-cdk-examples#249]
Hello,

I am using AWS CDK with Python.

I can't find any reference or examples to add "Tags" to EC2 instances via CDK.

Please provide some examples or references. 

Thanks,
Arun Sasidharan

**Comment by richardhboyd** [comment]
Adding Tags is covered here. 

https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

**Comment by shaftoe** [comment]
I think this might help: https://docs.aws.amazon.com/cdk/latest/guide/tagging.html

There are examples for all the main languages

**Comment by arunssasidhar** [comment]
Thanks for the support!
