### ISSUE TITLE
Need some examples for adding aws ssm Maintenance Window Task

### ISSUE THREAD

**Issue by arunssasidhar** [aws-samples/aws-cdk-examples#250]
Hi,

I am using AWS CDK with Python.

I am trying to create aws ssm Maintenance Window task with following code.

``` typescript
ssm_maint_window_task = ssm.CfnMaintenanceWindowTask(
            self, 'MaintenanceWindowTaskDemo',
            max_concurrency='5',
            max_errors='5',
            priority=1,
            targets=[{'key': 'WindowTargetIds', 'values': [ssm_maint_window.ref]}],
            task_arn='AWS-RunPatchBaseline',
            task_type='RUN_COMMAND',
            window_id=ssm_maint_window.ref,
            name='MaintenanceWindowTaskDemo',            
task_parameters=ssm.CfnMaintenanceWindowTask.MaintenanceWindowRunCommandParametersProperty(
	parameters= {
		'name' : 'Operation', 
		'values' : ['Install']
}))
```

However the "task_parameters" is not working as expected and throwing following error.

```
1/2 | 11:13:39 AM | UPDATE_FAILED        | AWS::SSM::MaintenanceWindowTask       | MaintenanceWindowTaskDemo Unrecognized field "values" (class com.amazonaws.services.ssm.model.MaintenanceWindowTaskParameterValueExpression), not marked as ignorable (one known property: "Values"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.amazonaws.services.ssm.model.UpdateMaintenanceWindowTaskRequest["TaskParameters"]->java.util.LinkedHashMap["parameters"]->com.amazonaws.services.ssm.model.MaintenanceWindowTaskParameterValueExpression["values"])
```

I also need to pass timeout parameter to the "task_parameters"

Please support.

Thanks,
Arun Sasidharan

**Comment by SomayaB** [comment]
Hi @arunssasidhar, thanks for opening an issue. This repo is a good place to ask for new examples to be added but if you need actual guidance on an issue, a better place would be to ask people on stackOverflow and if you still don't get the help you need you can ask on the main CDK repo aws/aws-cdk.

**Comment by SomayaB** [comment]
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Comment by elgamala** [comment]
I am going to provide a concrete example for MaintenanceWindow in python

**Comment by ddarling85** [comment]
Hi @elgamala.  Were you able to get something put together in Python yet?  I'm new to the CDK and Python, but just starting to work on creating a Maintenance Window and Task.  If you have some code I could review that would be awesome.  

Thanks
