### ISSUE TITLE
ECS Patterns and Associating an SSL Cert with Network Load Balancer

### ISSUE THREAD

**Issue by wbprice** [aws-samples/aws-cdk-examples#253]
### The Question

I'm planning to use the Network Load Balanced EC2 Service defined in ECS Patterns:

https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/ecs/ecs-network-load-balanced-service/index.ts#L26-L32

Behind the scenes somewhere, this creates a network load balancer.  I want to associate a given SSL cert with this load balancer.  How would I go about doing this with AWS-CDK?

### Environment

  - **CDK CLI Version:** 1.26.0 (build e251651)
  - **Example:** ecs-network-load-balanced-service
  - **Example Version:** 1.0.0
  - **OS:** OSX
  - **Language:** Typescript

**Comment by hencrice** [comment]
Hey @wbprice . Cert can be used with [ALB](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ecs-patterns.ApplicationLoadBalancedFargateService.html). However, there's currently no easy way to do it with NLB. I will mark this as a feature request

**Comment by hencrice** [comment]
@SomayaB Could you mark this as a feature request and remove the "needs-triage" label?
