### ISSUE TITLE
Add support for input transformer to `aws-events-targets.EcsTask`

### ISSUE THREAD

**Issue by shaftoe** [aws-samples/aws-cdk-examples#254]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I'm trying to setup an integration between CloudTrail events and an ECS Fargate task following the example from [this article](https://medium.com/@bowbaq/trigger-an-ecs-job-when-an-s3-upload-completes-3559c44c37d1) (scroll to the very bottom, the relevant `Terraform` snippet is the last one, e.g. `input_transformer` stanza).

Apparently it's not possible or at least I can't figure out how to make it from the [Python docs](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_events_targets/EcsTask.html) for `aws-events-targets.EcsTask`.

Basiclaly I'd like to add something like this as `ContainerOverride` to a `Trail` object with `on_cloud_trail_event`:

```python
aws_events_targets.ContainerOverride(
    container_name=container.container_name,
    environment=[
        aws_events_targets.TaskEnvironmentVariable(
            name="SRC_BUCKET",
            value="$.detail.requestParameters.bucketName",
        ),
        aws_events_targets.TaskEnvironmentVariable(
            name="SRC_KEY",
            value="$.detail.requestParameters.key",
        ),
    ],
)
```

Ideas?

### Environment

  - **CDK CLI Version:** 1.27.0 (build a98c0b3)
  - **OS:** OSX Mojave
  - **Language:** Python

**Comment by hencrice** [comment]
@shaftoe I believe what you are looking for is https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_events/RuleTargetInput.html

Example: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_events.README.html#rule

**Comment by hencrice** [comment]
@SomayaB It does not seem like I have the permission to change the label on this issue. Could you give me the permission?

**Comment by SomayaB** [comment]
Closing for now since the issue seems to have been addressed. Feel free to reopen if that's not the case.

**Comment by shaftoe** [comment]
@hencrice yeah sorry for the late, I didn't have the chance yet to try it out but it looks like you pointed me into the right direction, many thanks

**Comment by johns1342** [comment]
To save future travelers that land here trying understand how to wire up dynamic environment variables wtih `aws_events_targets.EcsTask`, here are the changes I made to @shaftoe's example to get it to work.  It uses **`aws_events.EventField.from_path()`** instead of **`aws_events.RuleTargetInput()`** as suggested above:

```python
aws_events_targets.ContainerOverride(
    container_name=container.container_name,
    environment=[
        aws_events_targets.TaskEnvironmentVariable(
            name="SRC_BUCKET",
            value=aws_events.EventField.from_path("$.detail.requestParameters.bucketName"),
        ),
        aws_events_targets.TaskEnvironmentVariable(
            name="SRC_KEY",
            value=aws_events.EventField.from_path("$.detail.requestParameters.key"),
        ),
    ],
)
```

It would be quite helpful if the [doc string](https://github.com/aws/aws-cdk/blob/7966f8d48c4bff26beb22856d289f9d0c7e7081d/packages/%40aws-cdk/aws-events-targets/lib/ecs-task-properties.ts#L55) mentioned `aws_events.EventField.from_path()` was the way, or at least a way, to generate a `valuePath`.

**Comment by cbromberg** [comment]
Yes - please add documentation or at least a link how to find more info. The current documentation is only mentions valuePath which isn't obvious what it is. (This issue is basically the same https://github.com/aws/aws-cdk/issues/3445)
