### ISSUE TITLE
More example that import existing resources

### ISSUE THREAD

**Issue by trondhindenes** [aws-samples/aws-cdk-examples#259]
### General Information
The hardest part for me in CDK is dealing with existing resources. In real life scenarios it is very uncommon that each app has their own ecs cluster, vpc, etc. These examples are nice and all, but they tend to illustrate the "happy path" where all resources can be defined in a single stack.

Please implement more examples where existing vpc are imported, existing ecs clusters and ALBs are used to deploy a service, and so on. That's the real pain in developing with CDK.

**Comment by NGL321** [comment]
#270 is asking for a fairly specific example of this. There is an update on the way, but I am going to use that issue as a stand-in for this addition.

😸
