### ISSUE TITLE
real examples of architecture

### ISSUE THREAD

**Issue by SomayaB** [aws-samples/aws-cdk-examples#271]
### General Information

_Originally posted by @andrefedev in https://github.com/aws/aws-cdk/issues/7055

"It is difficult to find an architecture where you can have tens of stacks with thousands of functions that represent microservices for an e-commerce store. How can you live the cdk code with the application source code, if each one has different environments, package.json, layers, eslint and other configurations. Thank You."

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by NGL321** [comment]
Hey @andrefedev,

What are you looking for in particular here? I'm hearing that you want an example of a microservice architecture in CDK?
I'm just trying to figure out what the effort would be to implement so we can put it on our backlog.

TIA!
😸

**Comment by SomayaB** [comment]
Closing for now since there hasn't been a response in a while. Feel free to reopen.
