### ISSUE TITLE
Region parameter missing in static-site aws-cdk example

### ISSUE THREAD

**Issue by mathieudevos** [aws-samples/aws-cdk-examples#292]
### What is the problem?
Deploying the static website example to any region other than `us-east-1` fails due to the certificate not being created in that region

### Reproduction Steps
Set region to anything but `us-east-1`
Deploy the cdk example
Expected: static website deployed
Outcome: cloudfront cannot find the certificate, stack rollback

**Comment by NGL321** [comment]
Thanks for reporting this bug! I will give the PR a review and that should close out this issue.

😸 😷
