### ISSUE TITLE
Error running cdk deploy on capitalize-string

### ISSUE THREAD

**Issue by kairs** [aws-samples/aws-cdk-examples#294]
### What is the problem?
Running the "capitalize-string" causes an error in "cdk deploy"
https://github.com/aws-samples/aws-cdk-examples/tree/master/csharp/capitalize-string#this-project

Ref: MSBUILD : error MSB1008: Only one project can be specified.

This seems to be related to cdk.json (https://github.com/aws-samples/aws-cdk-examples/blob/master/csharp/capitalize-string/cdk.json) where 2 builds are specified

### Reproduction Steps
Clone the repository and follow the readme here: 
https://github.com/aws-samples/aws-cdk-examples/tree/master/csharp/capitalize-string#build--deploy

### Verbose Log

   cdk deploy
   (node:24072) ExperimentalWarning: The fs.promises API is experimental   `
   Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
   Copyright (C) Microsoft Corporation. All rights reserved.
   
   MSBUILD : error MSB1008: Only one project can be specified.
   Switch: dotnet
   
   For switch syntax, type "MSBuild -help"
   Subprocess exited with error 1

### Environment

  - **CDK CLI Version:** 1.41.0 (build 9e071d2)
  - **Example:** capitalize-string
  - **Example Version:** 
  - **OS:** Windows 10
  - **Language:** csharp

**Comment by bcreedon** [comment]
I ran into the same problem. Changed the cdk.json to this, and it worked:

{
    "app": "dotnet run -p src/CapitalizeString/CapitalizeString.csproj"
}

**Comment by asoursos** [comment]
Try changing ; to && like:

"app": "dotnet publish -c Release CapitalizeStringHandler/src/CapitalizeStringHandler && dotnet run -p src/CapitalizeString"
