### ISSUE TITLE
Please update new rule.addTarget example from lambda-cron

### ISSUE THREAD

**Issue by w2fong** [aws-samples/aws-cdk-examples#299]
### The Question
Example from lambda-cron/index.ts seems to be out dated compare to recent change of "addTarget" to (handler: IFunction, prop?: LambdaFunctionProps )

I am referring to the following example:
https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/lambda-cron/index.ts

### Environment
  - **Example:** 
Error message "Argument of type 'Function' is not assignable to parameter of type 'IFunction'.ts"
`    rule.addTarget(new targets.LambdaFunction(lambdaFn));
`
  - **Example Version:**
https://registry.npmjs.org/@aws-cdk/aws-events-targets/-/aws-events-targets-1.44.0.tgz

  - **OS:** 
OSX Catalina Version 10.15.2

  - **Language:** 
TypeScript

### Other information 
n/a

**Comment by NGL321** [comment]
Hey @w2fong,

Sorry for the delay. The error message `Argument of type 'X' is not assignable to parameter of type 'IX'` is typically indicative that your packages are using 2 different versions of the CDK.

Could you check the versions and try again? (I was unable to reproduce the issue you are encountering)

**Comment by dgonzalez** [comment]
This still happens to me.
