### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by SoManyHs** [aws-samples/aws-cdk-examples#300]
Would it be possible to change the name of the default branch in this repo from "master" to "mainline" or some other alternative? This is already a convention at Amazon internally, and would be compliant with the recommendation by the IETF: https://tools.ietf.org/id/draft-knodel-terminology-00.html

Thanks!

Related: https://github.com/aws/jsii/issues/1733, https://github.com/aws/aws-cdk/issues/8485

**Comment by richardhboyd** [comment]
I strongly support this!!!

**Comment by SoManyHs** [comment]
Any movement on this? @SomayaB @NGL321

**Comment by kaizio** [comment]
Fixed
