### ISSUE TITLE
A single multistack creates multiple pipline to deploye single s3 bucket - How?

### ISSUE THREAD

**Issue by jayakumarselvan** [aws-samples/aws-cdk-examples#303]
**Python CDK**
A single multistack creates multiple pipeline.
The all pipelines want to deploy the code in single s3 bucket. 
Now i'm getting bucket name already exists in stack.
How to achieve this scenario???

**Comment by skinny85** [comment]
Hello @jayakumarselvan ,

I believe you're looking for the `s3.Bucket.from_bucket_attributes()` method: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_s3/Bucket.html#aws_cdk.aws_s3.Bucket.from_bucket_attributes

Thanks,
Adam

**Comment by jayakumarselvan** [comment]
Thanks Adam,
`target_bucket = s3.Bucket.from_bucket_arn(self, "BucketByArn", "arn:aws:s3:::**_BUCKET_NAME_**")`
Got it. I Made by using ARN
