### ISSUE TITLE
AWS CDK pipeline  - Insufficient permissions while pulling source from GitHub

### ISSUE THREAD

**Issue by jayakumarselvan** [aws-samples/aws-cdk-examples#307]
I'm trying to make pipeline through AWS CDK with python.

That pipeline simply pulling source from GitHub and deploy to S3 bucket.

When I'm deploy the pipeline (like 'cdk deploy cdkabc'), the pipeline is creting. 

But trying to release the pipeline, i'm getting error
```
**Insufficient permissions**
Unable to connect to the GitHub repository '_reponame_'. Use the console to reconnect your pipeline to GitHub.
```

The I'm editing the source same pipeline through AWS Console and connect to the GitHub. It is working.

Reference code: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions.README.html#github

Kindly share the solution or links to resolve this.

**Comment by SomayaB** [comment]
Hi @jayakumarselvan, thanks for opening an issue. This repo is for examples that are not included in the documentation and so your issue belongs in the main CDK repo. I've opened a new issue for you there https://github.com/aws/aws-cdk/issues/8731. I will be closing this issue so please follow along there. Thank you!
