### ISSUE TITLE
sample code for creating mysql aurora serverless instance in existing ec2 vpc.

### ISSUE THREAD

**Issue by githbsingh** [aws-samples/aws-cdk-examples#308]
### The Question

I can see the similar sample code in python under rds but not for typescript.
### Environment

  - **CDK CLI Version:**  1.46.0 (build 63860b2)
  - **Example:** Shared Image below
  - **Example Version:** 
  - **OS:**  Windows 10
  - **Language:** TypeScript 

### Other information 

![pythonExample](https://user-images.githubusercontent.com/47235658/85509588-e290dd80-b613-11ea-98ba-285f9d6eed23.JPG)

**Comment by SomayaB** [comment]
Hi @githbsingh, thanks for opening this issue. I'm not sure what your ask is though. Do you need guidance, are you asking for a new example to be added or are you contributing your own example?

**Comment by githbsingh** [comment]
Hi Soumya,

I want new example to be added for creating RDS under existing ec2 vpc
instance in typescript/python.

Please let me know if further information is needed.

Thank You.
Regards,
Manohar Kumar Singh.

**Comment by rahul-amzn** [comment]
Hi @githbsingh Planning to pick it up and can I use the latest CDK CLI version?

**Comment by rahul-amzn** [comment]
> Hi @githbsingh Planning to pick it up and can I use the latest CDK CLI version?

@skinny85 Can you please suggest CDK CLI version?

**Comment by skinny85** [comment]
I would suggest using the latest CDK version 🙂.

**Comment by kaiz-io** [comment]
[CDK API for Serverless Cluster](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.ServerlessCluster.html) docs already has this as an example.
