### ISSUE TITLE
Lambda gradual deploy example, with automated roll back

### ISSUE THREAD

**Issue by dave-graham** [aws-samples/aws-cdk-examples#309]
### Description
Is there any chance you could create a lambda based example of gradual deploys with automated roll back if there are issues?

### Proposed Solution
The key functionality is available in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html but I would love to be able to use CDK instead. It allows canary deploys and an automated roll back if error levels trigger a cloudwatch alert.

**Comment by nija-at** [comment]
As far as I know, this doesn't exist in the CDK and will have to be built as a brand new construct.

It's also not clear if this is something we would add here as part of the CDK. The AWS solutions team has started building up a library of useful patterns like this - https://github.com/awslabs/aws-solutions-constructs.

It may be worth opening an issue in their repo. Leaving this open for now.
