### ISSUE TITLE
[custom-resources] cfnresponse.send in python using CDK

### ISSUE THREAD

**Issue by amitksahu** [aws-samples/aws-cdk-examples#311]
## :question: Guidance Question
As per the latest documents "https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html" cfnresponse is now part of CDK construct. Could you please share some examples of how to implement is using python.
How to call cfnresponse.send? 

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by SomayaB** [comment]
Hi @amitksahu, the duplicate issue you've opened in the main CDK repo was the right place to ask for guidance. The examples repo is for additional examples included in this repo and not in the API reference. We can keep this issue open as a feature request to add an example for this though.

**Comment by NGL321** [comment]
As noted in the question on the main repo, you should not need to interface with `cfnresponse`.

From eladb:

> If you are using `@aws-cdk/custom-resources.Provider` to implement your custom resource, you don't need to interact with `cfnresponse`. 
>
>If the operation succeeds, your lambda handler should return, and optionally return `PhysicalResourceId` and `Data` (attributes). The provider framework will issue a SUCCESS response to CFN. 
>
>If the operation fails, your code should simply throw an error, and the provider framework will issue a FAILED response to CFN.
