### ISSUE TITLE
Add EKS example (including EKS fargate)

### ISSUE THREAD

**Issue by rustlingwind** [aws-samples/aws-cdk-examples#322]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by kishoreallwynraj** [comment]
I can contribute a C# example for this feature request.

**Comment by kishoreallwynraj** [comment]
@NGL321 i have summited a PR with a C# example for EKS. This is based on EC2 nodes.
