### ISSUE TITLE
is this warning still needed?

### ISSUE THREAD

**Issue by thedevopsguyblog** [aws-samples/aws-cdk-examples#327]
https://github.com/aws-samples/aws-cdk-examples/blob/a4cfbd7ec683ece8a20cdceae275a0248a994fc7/typescript/ecs/cross-stack-load-balancer/split-at-targetgroup.ts#L46

Looks like we are at ~1.54 so this can be updated

**Comment by SomayaB** [comment]
@thedevopsguyblog thanks for the catch!
