### ISSUE TITLE
Example: setting up a private integration with a alb/nlb using new aws-apigatewayv2 module

### ISSUE THREAD

**Issue by mscheer93** [aws-samples/aws-cdk-examples#329]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Since the migration of HTTP API into the new [aws-apigatewayv2](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html) module, it is unclear to me how to use the module to set up a private integration via VPCLink with an alb/nlb using the new aws-apigatewayv2 module when adding routes to the api.
The example shown in [Issue 8066](https://github.com/aws/aws-cdk/issues/8066) doesn't fit the new library.
```typescript
import * as apiv2 from '@aws-cdk/aws-apigatewayv2';
import * as apigw from '@aws-cdk/aws-apigateway';


const api = new apiv2.HttpApi(this, "testingApi", {
      apiName: "testingApi",
})

// declare API routes integrations
const link = new apigw.VpcLink(this, 'link', {
  targets: [nlb]
});
const integration = new apigw.HttpIntegration("",{
  httpMethod: apiv2.HttpMethod.ANY,
  options: {
    connectionType: apigw.ConnectionType.VPC_LINK,
    vpcLink: link
  },
  proxy: false
})

api.addRoutes({
  integration: integration,
  methods: [apiv2.HttpMethod.GET, apiv2.HttpMethod.DELETE, apiv2.HttpMethod.POST, apiv2.HttpMethod.OPTIONS, apiv2.HttpMethod.PUT],
  path: "/somePath"
})

// -> throws ...Type 'HttpIntegration' is not assignable to type 'IHttpRouteIntegration'... error
```
The ```addRoutes()``` call requires type 'IHttpRouteIntegration', but I can't figure out how to use the [HTTP Proxy Integration](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-apigatewayv2.HttpProxyIntegration.html) to set up a private integration for an alb/nlb linked to routes.
### Proposed Solution

A simple code example with just one stack containing the new HTTP API and a linked alb/nlb via private integration using the
[aws-apigatewayv2](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-apigatewayv2-readme.html) would be perfect :)

### Environment

  - **CDK CLI Version:** 1.61.0
  - **OS:** all
  - **Language:** TypeScript

**Comment by nija-at** [comment]
We don't have support for vpc link in the `aws-apigatewayv2` module. 

I've opened an issue to track this - https://github.com/aws/aws-cdk/issues/10119. Examples will be available once this feature has been implemented.
