### ISSUE TITLE
Fargate Service with NLB missing securitygroup details

### ISSUE THREAD

**Issue by kazijn** [aws-samples/aws-cdk-examples#334]
### What is the problem?
When running the ECSFargateLoadBalanced sample in Java there is a statement missing to add the correct ingress rule to the fargate linked securitygroup.

### Reproduction Steps
Just run the sample and you will not be able to connect to the sample app via the public url.

### Environment

  - **CDK CLI Version:** 1.62.0
  - **Example:** fargate-load-balanced-service
  - **Example Version:** ?
  - **OS:** all
  - **Language:** Java

**Comment by kazijn** [comment]
I don't seem to be able to add a pull request to this issue but the missing line is: 
`fargateService.getService().getConnections().allowFromAnyIpv4(Port.tcp(80));`

**Comment by NGL321** [comment]
Thanks for reporting, I will add this fix!

😸 😷

**Comment by kaiz-io** [comment]
Was fixed.
