### ISSUE TITLE
update fargate-service-with-efs

### ISSUE THREAD

**Issue by kastork** [aws-samples/aws-cdk-examples#359]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Request example update to use cdk 1.71.0 or later.

Based on the documentation, CDK now supports

* The creation of EFS access points
* EFS mounts in task definitions
* The ability to set the Fargate platform verison in a `FargateService`

So it seems like the example (`typescript/ecs/fagate-service-with-efs`) is demonstrating an out of date approach that relies on custom resources and is more complicated than it needs to be with current CDK versions.

 
### Proposed Solution

Update the example to use the constructs and properties available in CDK 1.71.0 or later.

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:** 

### Other information 

I've tried to do this myself, but either due to a bug or my own lack of understanding, I can't get the generated stack to work (`Unknown volume 'fsap-xxxx'` (even though that `fsap` has been created.))

**Comment by kastork** [comment]
@maskerade Giving you a ping in case you're interested -- since the example originated with your PR.

**Comment by kaiz-io** [comment]
This was fixed.
