### ISSUE TITLE
S3 Bucket.FromBucketName returns invalid interface 

### ISSUE THREAD

**Issue by TheMurxOr** [aws-samples/aws-cdk-examples#367]
### On Function Bucket.FromBucketName retrieval of object IBucketProxy
When I try to retrieve an already existing Bucket from the S3 inventory, via the FromBucketName method
 in  package Amazon.CDK.AWS.S3  Version="1.74.0"
I retrieve the unexpected object IBucketProxy instaead of IBucket.
This results in the typecast error:
```console
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Amazon.CDK.AWS.S3.IBucketProxy' to type 'Amazon.CDK.AWS.S3.Bucket'.
```
### Reproduction Steps
Create the following Stack snippet twice:
 
```csharp
public class AwsCdkDeployStack : Stack
{
    internal AwsCdkDeployStack(Construct scope, string id, IStackProps props = null) : base(scope, id, props)
    {
        var bucket =(Bucket)  Bucket.FromBucketName(this, "NavigationSourceBucket", "navigation-source-bucket");  
        var myNavigationSourceBucket = bucket ??
        new Bucket(this, "NavigationSourceBucket", new BucketProps{
                Versioned = true,
                BucketName = "navigation-source-bucket",
                Encryption = BucketEncryption.S3_MANAGED,
        });
    }
}
```

### Environment

  - **CDK CLI Version:** 1.74.0 (build e86602f)
  - **Example:**
  - **Example Version:** Amazon.CDK.AWS.S3  1.74.0
  - **OS:** OSX
  - **Language:** C#

**Comment by indrora** [comment]
Closing: CDKv1, wrong repo. 

If this is still a problem, please report it in aws/aws-cdk rather than here.
