### ISSUE TITLE
Exemplify use of core.Stage class

### ISSUE THREAD

**Issue by kastork** [aws-samples/aws-cdk-examples#370]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

The term "Stage" is very overloaded across AWS services.  CDK adds yet another stage in the form of `@aws-cdk/core.Stage`.

So far, the documentation for CDK doesn't say much about Stage or how it should be used in practice.

### Proposed Solution

An example project in this repository that demonstrates good practice using Stage would be useful (along with better documentation in the API Docs.

### Environment

  - **CDK CLI Version:**  1.76.0
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by NGL321** [comment]
Hey @kastork,

After a quick review, I agree that the documentation of `Stage` does not quite fully encapsulate the concept. With that said, I dont think that an example will resolve this problem though.

Could you give more details about what you think is missing/incomplete/unhelpful so we can work on improving it?

@Jerry-AWS any thoughts on this?

😸 😷

**Comment by kastork** [comment]
I suppose I'm looking for a use-case.  When would I use this construct and what does it buy me?  The example would still be useful just to demonstrate how it is useful (IMO).

**Comment by kaiz-io** [comment]
[Pipelines](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.pipelines-readme.html) shows and example of using Stage. I don't know of a use outside of pipelines.
