### ISSUE TITLE
Add samples on elastic search [TypeScript]

### ISSUE THREAD

**Issue by zafarella** [aws-samples/aws-cdk-examples#374]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

There are no samples on elastic search. The basics are clear, however adding permissions, etc are problematic for people not familiar with the SDK/CDK.

### Environment

  - **CDK CLI Version:** 
    ```
         ➜ cdk version
           (node:18137) ExperimentalWarning: The fs.promises API is experimental
			1.78.0 (build 2c74f4c)
	```
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  	cross platform
  - **Language:** 
    * TypeScript

**Comment by oflouis** [comment]
Feel free to assign this issue to me if you don't mind.
In my project, I'm using AWS OpenSearch which I have built with CDK.
I can give you an example of included these:
- using private VPC
- using basic authentication for security - master user
- adding access control - security group and policy statement

**Comment by kaiz-io** [comment]
[CDK docs for elasticsearch](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticsearch-readme.html) has examples now
