### ISSUE TITLE
Update Typescript example for Custom Resource to use non-deprecated constructs

### ISSUE THREAD

**Issue by its-mirus-lu** [aws-samples/aws-cdk-examples#388]
### General Information

* [ X] :wave: I may be able to implement this feature request

* [X ] :warning: This feature might incur a breaking change 

### Description

The existing Typescript example for custom resources uses deprecated constructs aws-cloudformation.CustomResource and aws-cloudformation.CustomResourceProvider.  I propose to update the code example to use non-deprecated constructs.

### Proposed Solution

Update the existing code sample to use non-deprecated constructs.

### Environment

  - **CDK CLI Version:**  1.89.0
  - **Example:**  typescript/custom-resource
  - **Example Version:**  1.0.0
  - **OS:**  all
  - **Language:**  Typescript

### Other information 

Further investigation is required to determine what needs to be modified to bring the sample code up to date with CDK 1.89.0 and later

**Comment by miruslu-amazon** [comment]
I've discovered how this example could be updated to use the custom resource provider framework from @aws-cdk/custom-resources: https://docs.aws.amazon.com/cdk/api/latest/docs/custom-resources-readme.html

Would it be better to provide a separate example to use aws-cdk/custom-resources or update the existing custom resource example?
