### ISSUE TITLE
AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException

### ISSUE THREAD

**Issue by BrandonMichaelWebb** [aws-samples/aws-cdk-examples#402]
### The Question

AWSCDK and AWSCLI have both been installed, and when deploying the CDK application I get the following error message:

8:37:22 AM | CREATE_FAILED        | AWS::Cognito::UserPoolDomain                | ICS_USERS_POOL_DOMAIN
Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: f3f0b188-1063-4f83-a884-e810588a749c; Proxy: null)
8:37:24 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack                  | ImageContentSearch

However I do not have any domains configured so unsure as to why this error is being generated.

### Environment

  - **CDK CLI Version:** 1.94.1 (build 60d8f91)  
  - **Example:** Image Search Demo Application
  - **OS:**  MacOS 
  - **Language:** Python

**Comment by gshpychka** [comment]
@NGL321 any idea why this can happen?

**Comment by poul-kg** [comment]
@BrandonMichaelWebb depends on how you're specifying your domain name, if you're doing it via `domainPrefix` than make sure it's globally unique. I had the same problem today, as I was trying to use `development` as my `domainPrefix` and looks like that https://development.auth.ap-southeast-2.amazoncognito.com domain is already taken by someone. So I've updated my `domainPrefix` to something like `aaaa-development` and it worked.

**Comment by elginlam-amazon** [comment]
You can use the node.addr property to create a unique domainPrefix.

```
cognitoDomain: {
                domainPrefix: `${this.node.addr}`
}
```

**Comment by peterwoodworth** [comment]
Yes - the domain must be globally unique or you may run into this failure. Thanks for the answer @poul-kg
