### ISSUE TITLE
jsii.errors.JSIIError: 'cidr' property must be a concrete CIDR string, got a Token (we need to parse it for automatic subdivision)

### ISSUE THREAD

**Issue by karthiksonti24** [aws-samples/aws-cdk-examples#411]
### The Question

I'm trying to launch a vpc using cdk(python). I'm passing CIDR Range using a parameter which is giving this error. 

```jsii.errors.JavaScriptError: 
  Error: 'cidr' property must be a concrete CIDR string, got a Token (we need to parse it for automatic subdivision)
      at new Vpc (/tmp/jsii-kernel-TwfBFg/node_modules/@aws-cdk/aws-ec2/lib/vpc.js:335:19)
```

### Environment

  - **CDK CLI Version:** 1.95.0
  - **Example:** 
  - **Example Version:** 
  - **OS:**  Ubuntu
  - **Language:**  Python

### Other information 

My code snippet.
```

        vpc_cidr = cdk.CfnParameter(self, "vpcCidr", type="String",
        	description="The name of Amazon VPC where infrastructure will be created")
        vpc = ec2.Vpc(self, "vpc", cidr=vpc_cidr.value_as_string)
```
and that's how I'm passing it .

```cdk deploy demo --parameters s3BucketName=tests3bucketcdk --parameters vpcCidr=10.0.0.0/16
```

Someone please help me.

**Comment by aserour** [comment]
Hi @karthiksonti24,

You can achieve more or less the same using context parameters.

CDK Stack snippet
```python
ec2.Vpc(
    self, 'AwesomeVPC',
    cidr=self.node.try_get_context('VpcCIDR')
)
```
Then you can pass the VPC CIDR dynamically as follows
```shell
cdk synth -c "VpcCIDR=10.0.0.0/16"
```

**Comment by karthiksonti24** [comment]
@aserour Thanks for the suggestion.
