### ISSUE TITLE
Typescript EC2 Instance Example

### ISSUE THREAD

**Issue by schuettc** [aws-samples/aws-cdk-examples#416]
### General Information
* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change 

### Description
A Typescript example that will deploy an EC2 instance and allow a user to connect easily.

### Proposed Solution
https://github.com/schuettc/aws-cdk-examples/tree/master/typescript/ec2-instance

### Environment
  - **CDK CLI Version:** 1.95.2 (build d6784aa)
  - **Example:** Typescript EC2 Instance
  - **OS:** all
  - **Language:**  TypeScript

**Comment by ryparker** [comment]
Resolved in https://github.com/aws-samples/aws-cdk-examples/pull/421
