### ISSUE TITLE
ecs/cross-stack-load-balancer/split-at-target-group creates incorrect target type for Fargate

### ISSUE THREAD

**Issue by markilott** [aws-samples/aws-cdk-examples#423]
### What is the problem?
ApplicationTargetGroup creates the group with the default target type of Instance (if no targets are registered in the same stack).

A target type of "IP" is required for Fargate, which is used in the rest of the example.

### Reproduction Steps
Deploy using the current example code. Target Type will be created as Instance, and the following registration of Fargate service will fail.

### Environment

  - **CDK CLI Version:** 1.100
  - **Module Version:** 1.100
  - **Node.js Version:** 14.x
  - **Language:** Typescript

### Other information 
Should be:

```javascript
this.targetGroup = new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      vpc: props.vpc,
      port: 80,
      targetType: elbv2.TargetType.IP, // default is Instance if no targets are registered in the same stack
    });
```

**Comment by indrora** [comment]
Closing: CDKv1 is out of support.

If this is a problem with a current example, please give the specific example. Otherwise, file a bug report with aws/aws-cdk.
