### ISSUE TITLE
Request to add content: rekognition_lambda_s3_trigger

### ISSUE THREAD

**Issue by mullicak** [aws-samples/aws-cdk-examples#425]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
 I created a sample python CDK code that will deploy an S3 bucket, a Python Lambda script that will classify an image and be triggered by S3 object add, and then write the results back to S3 as well as DynamoDB and CloudWatch Logs.

### Proposed Solution
 CDK app written in Python, github.com/aws-samples/aws-cdk-examples/pull/424

### Environment

  - **CDK CLI Version:**  1.100.0 (build d996c6d)
  - **Example:**  rekognition_lambda_s3_trigger
  - **Example Version:**   1
  - **OS:**  all
  - **Language:**  Python

### Other information 
  github.com/aws-samples/aws-cdk-examples/pull/424

**Comment by NGL321** [comment]
Resolving due to merged PR
