### ISSUE TITLE
Sample for CloudWatch Dashboards (Python)

### ISSUE THREAD

**Issue by marclyo** [aws-samples/aws-cdk-examples#427]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
A sample that demonstrates how to a user can create CloudWatch Dashboards and add widgets using CDK in Python

### Proposed Solution

Pull Request: https://github.com/aws-samples/aws-cdk-examples/pull/426

### Environment

  - **CDK CLI Version:**  1.99.0
  - **Example:**  lambda-cloudwatch-dashboard
  - **Example Version:**  1
  - **OS:**  all
  - **Language:**  Python

### Other information 

Pull Request: https://github.com/aws-samples/aws-cdk-examples/pull/426

**Comment by sebsonjura** [comment]
I could chip this in as typescript
