### ISSUE TITLE
CDK example: ecs-service-with-advanced-nlb-config

### ISSUE THREAD

**Issue by namedgraph** [aws-samples/aws-cdk-examples#446]
I'm trying to follow the examples in https://github.com/aws/aws-cdk/issues/4463 but with `NetworkLoadBalancedEc2Service` and can't get the target registration to work.

Can we please get complex config examples for the `NetworkLoadBalancer`? Something like `ecs-service-with-advanced-nlb-config`, in addition to [`ecs-network-load-balanced-service`](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/ecs-network-load-balanced-service) and as a mirror of ALB's [`ecs-service-with-advanced-alb-config`](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ecs/ecs-service-with-advanced-alb-config).

**Comment by namedgraph** [comment]
People complain that the NLB setup is under-documented, not only under CDK but in general:
https://stackoverflow.com/questions/62578770/aws-network-load-balancers-and-ephemeral-ports

**Comment by jfan9** [comment]
[ecs-network-load-balanced-service](https://github.com/aws-samples/aws-cdk-examples/tree/main/typescript/ecs/ecs-network-load-balanced-service) example covers this feature: #446

**Comment by kaiz-io** [comment]
+1 this is covered in existing example
