### ISSUE TITLE
Adding Typescript CDK Example for Lambda Managing S3 Event Notifications

### ISSUE THREAD

**Issue by phch** [aws-samples/aws-cdk-examples#447]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I am submitting a feature request to add in a Lambda managing S3 event notifications CDK example. I am part of the AWS organization and submitting this as part of my I&A blog post.

S3 event notifications in CDK can only be managed by buckets that are owned by the stack. If you have a shared bucket, and you use CDK to manage the notifications it does not behave correctly (e.g. if ServiceAStack and ServiceBStack configure their own notification on an S3 bucket, it does not create the S3 event notifications as expected).

### Proposed Solution

This solution will use a Lambda function to manage the S3 event notifications. Service stacks can configure their own S3 event notifications on a shared bucket by using Cloudformation Custom Resource backed by a Lambda function. The example will show how to achieve this.

### Environment

  - **CDK CLI Version:**  1.105.0 (build 4813992)
  - **Example:**  lambda-manage-s3-event-notification
  - **Example Version:**  0.1.0
  - **OS:**  all
  - **Language:**  TypeScript

**Comment by phch** [comment]
https://github.com/aws-samples/aws-cdk-examples/pull/452
Open PR for this request

**Comment by NGL321** [comment]
Looks like this has actually been resolved. Closing

😸 😷
