### ISSUE TITLE
EventRule must be changed to Rule

### ISSUE THREAD

**Issue by dmonteiro-paddle** [aws-samples/aws-cdk-examples#45]
On the examples for python using the cdk, there's an example for lambda-cron that doesn't work when doing the cdk synth command.

AttributeError: module 'aws_cdk.aws_events' has no attribute 'EventRule'

After taking a look on the cdk code, i could verify that EventRule has been changed to Rule only.

https://github.com/awslabs/aws-cdk/blob/master/packages/%40aws-cdk/aws-events/lib/rule.ts

This is still not documented on the official cdk documentation and could affect all examples that uses EventRule for the various programming languages.

**Comment by simalexan** [comment]
@dmonteiro-paddle it should be fixed now. @eladb fixed those

**Comment by dmonteiro-paddle** [comment]
awesome!
