### ISSUE TITLE
Add example of api gateway s3 proxy

### ISSUE THREAD

**Issue by kastork** [aws-samples/aws-cdk-examples#453]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

Would like to have an example that demonstrates api gateway proxy of S3 resources.

The documentation for api gateway on the AWS website contains an example to proxy S3 resources.  The web console steps don't map in any obvious way to the constructs in cdk.  Although there is already an example for http proxy here in this repo, it really isn't much help for the S3 proxy use-case.

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by indrora** [comment]
Closing: stale.
