### ISSUE TITLE
An example of S3 Object Lambda in C#

### ISSUE THREAD

**Issue by OksanaH** [aws-samples/aws-cdk-examples#454]
### General Information

* [X ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
I was experimenting with S3Object Lambda in CDK for C# and would like to share the solution that worked for me in case it's useful for others. I think it would also be a good example of how L1 Constructs work and how to work with untyped objects in CDK for C#. Besides, I think in C# it's less straightforward that in Typescript.

### Proposed Solution
The example I have is here: https://github.com/OksanaH/s3ObjectLambda

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:** C#

### Other information 
@peterwoodworth tagging you just in case, as it was briefly discussed here: https://github.com/aws/aws-cdk/issues/14995 :)

**Comment by NGL321** [comment]
This is an interesting example. Could you outline what parts of the CDK you think it helps clarify and outline beyond implementing L1 and L2 constructs in tandem?

With a good description, I think we would be happy to merge this

😸 😷

**Comment by OksanaH** [comment]
Hi @NGL321 ,
Thanks for looking at this.

It helps to clarify how to define S3 Object Lambda and its components.

I think the description could be 'An implementation of S3 Object Lambda in CDK for C#'. 

 Should I create a PR with the code from my repo?

Thanks
