### ISSUE TITLE
Roll-your-own Neptune Workbench

### ISSUE THREAD

**Issue by jeffmaley** [aws-samples/aws-cdk-examples#464]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I'd like to add a sample that provisions an EC2 instance, a VPC, a Security Group, and an ALB. The EC2 instance would include a user-data script to install AWS Graph Notebook and nginx and would include an IAM policy to enable a psuedo-ABAC for the neptune-db:connect API call. This use case is for organizations that desire something like Neptune Workbench, but need to manage any deployed AMIs themselves.

### Proposed Solution

I have a working example.

### Environment

  - **CDK CLI Version:** 1.110.0 (build 32f00eb)
  - **Example:** ?
  - **Example Version:** ?
  - **OS:** All
  - **Language:** TypeScript

**Comment by peterwoodworth** [comment]
Hey @jeffmaley, if you have an example ready we'd love to review it! Can you share it with us?

**Comment by jeffmaley** [comment]
@peterwoodworth Here's the link to what I have - https://github.com/jeffmaley/ec2graphnotebook

**Comment by jeffmaley** [comment]
I wanted to follow-up and see if there was any movement.

**Comment by kaiz-io** [comment]
If this is still desired please reopen.
