### ISSUE TITLE
Argument of type 'Function' is not assignable to parameter of type 'IFunction' (2 years later)

### ISSUE THREAD

**Issue by SeanRenet** [aws-samples/aws-cdk-examples#475]
### What is the problem?
In the Typescript workshop, the example code throws the above error.

### Reproduction Steps
Just follow along with the workshop until you get to here.

```
import * as cdk from '@aws-cdk/core';
import * as lambda from '@aws-cdk/aws-lambda';
import * as apigw from '@aws-cdk/aws-apigateway';

export class CdkTypescriptWorkshopStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // defines an AWS Lambda resource
    const hello = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_10_X,    // execution environment
      code: lambda.Code.fromAsset('lambda'),  // code loaded from "lambda" directory
      handler: 'hello.handler'                // file is "hello", function is "handler"
    });

    // defines an API Gateway REST API resource backed by our "hello" function.
    new apigw.LambdaRestApi(this, 'Endpoint', {
      handler: hello
    });

  }
}
```
### Verbose Log
% cdk diff   
⨯ Unable to compile TypeScript:
lib/cdk-typescript-workshop-stack.ts:18:7 - error TS2322: Type 'Function' is not assignable to type 'IFunction'.
  Types of property 'role' are incompatible.
    Type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined' is not assignable to type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined'.
      Type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/role").IRole' is not assignable to type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/role").IRole'.
        Types of property 'grant' are incompatible.
          Type '(grantee: import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal, ...actions: string[]) => import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-la...' is not assignable to type '(grantee: import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal, ...actions: string[]) => import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/grant").Grant'.
            Types of parameters 'grantee' and 'grantee' are incompatible.
              Type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal' is not assignable to type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal'.
                Types of property 'addToPolicy' are incompatible.
                  Type '(statement: import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean' is not assignable to type '(statement: import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean'.
                    Types of parameters 'statement' and 'statement' are incompatible.
                      Type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-lambda/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to type 'import("/Users/seanrenet/Sites/AWS CLOUD DEVELOPMENT KIT/cdk-typescript-workshop/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
                        Types have separate declarations of a private property 'action'.

18       handler: hello
         ~~~~~~~

  node_modules/@aws-cdk/aws-apigateway/lib/lambda-api.d.ts:16:14
    16     readonly handler: lambda.IFunction;
                    ~~~~~~~
    The expected type comes from property 'handler' which is declared here on type 'LambdaRestApiProps'

Subprocess exited with error 1

### Environment

  - **CDK CLI Version:** 1.114.0 (build 7e41b6b)
  - **Example:**  AWS CDK Intro Workshop > TypeScript Workshop > Hello, CDK! > API Gateway
  - **Example Version:**  Not sure, whatever is at https://cdkworkshop.com/20-typescript/30-hello-cdk/300-apigw.html
  - **OS:** MacOs BigSur 11.2.3
  - **Language:** TypeScript

### Other information 
I figured out the problem is that npm i @aws-cdk/aws-apigateway installs version 1.114.0 which is incompatible with the rest of the code.  I changed the dependency to match the rest, deleted node_modules and redid npm i.  Or alternatively, just npm i @aws-cdk/aws-apigateway@1.113.0

Now it works.  Just posting for anyone else that has to stare at their screen for an hour wondering why the example code is not working.

  "dependencies": {
    "@aws-cdk/aws-apigateway": "1.113.0",
    "@aws-cdk/aws-lambda": "1.113.0",
    "@aws-cdk/aws-sns": "1.113.0",
    "@aws-cdk/aws-sns-subscriptions": "1.113.0",
    "@aws-cdk/aws-sqs": "1.113.0",
    "@aws-cdk/core": "1.113.0"
  }

**Comment by peterwoodworth** [comment]
Thank you for submitting this bug report! This isn't an issue with the workshop code however. As you found out, this was due to mismatching versions in your package.json. You most likely started this project when 1.113.0 was the current version and then installed apigateway after 1.114.0 released. Unfortunate, but I'm glad you figured it out 😄

**Comment by SeanRenet** [comment]
@peterwoodworth No.  I just started it 5 days ago.  It installs mismatching versions.

**Comment by peterwoodworth** [comment]
@SeanRenet the cdk workshop doesn't determine what versions you install with npm. npm install will install whatever the latest version is at the time you run the command. It's likely that it was updated between when you started the workshop and when you installed apigateway. Version 1.114.0 released about 5 days ago
