### ISSUE TITLE
Creating postGres full example (request)

### ISSUE THREAD

**Issue by brmur** [aws-samples/aws-cdk-examples#478]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
Customer is creating a postgres database using AWS CDK with VPC, subnets, security groups and parameters, and has requested  actual full-example. With VPC's, db subnets, parameters

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by peterwoodworth** [comment]
A full example would take a while, and is currently not at the top of our priority list. If the customer needs help doing this soon, I'd suggest trying to work through it themselves, and/or ask for help on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg), or post a guidance issue to the CDK Repo when stuck. 

I am marking this issue as p2, which means that we are unable to work on this immediately.

We use +1s to help prioritize our work, and are happy to revaluate this issue based on community feedback. You can reach out to the cdk.dev community on [Slack](https://join.slack.com/t/cdk-dev/shared_invite/zt-mso6p56d-qJp7SOTBvMaQuDrx7R2wHg) to solicit support for reprioritization.

**Comment by brmur** [comment]
@peterwoodworth  Thanks for you response. I've shared this issue with the requester.
