### ISSUE TITLE
Using Lambda Layers with Lambda Functions in CDK 

### ISSUE THREAD

**Issue by asadana** [aws-samples/aws-cdk-examples#486]
### General Information

* [X] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description

I'd like to add examples that demonstrate use of Lambda Layers with Lambda Functions as CDK components. In addition, demonstrate the language-specific folder structures that are used when create Lambda Layers as seen in [documentation](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html#configuration-layers-path).
This use case is quite common for enterprise deployments but not included as an example here.

### Proposed Solution

I am happy to make a PR for multiple languages, starting with Python for initial review/baseline before others.

### Environment

  - **CDK CLI Version:** 1.117.0 (build 0047c98)
  - **Example:** lambda-layer (*new*)
  - **Example Version:** 
  - **OS:** all
  - **Language:** all

**Comment by peterwoodworth** [comment]
We'd be happy to review an example if you create one!
