### ISSUE TITLE
Code Pipeline Tutorial

### ISSUE THREAD

**Issue by redixhumayun** [aws-samples/aws-cdk-examples#489]
### The Question
Is there a tutorial for setting up a basic Code Pipeline in this repository? I'm not particular about what the Pipeline does, a basic example of pulling from a GitHub repo, building using CodeBuild and deploying to an S3 bucket would do.

I am specifically interested in how to use Codestar Connection (like I can on the AWS console) to connect to my GitHub repo from AWS CDK.

**Comment by NGL321** [comment]
Hey @redixhumayun,

Sorry for the long delay here. There is a comprehensive tutorial on setting up a pipeline with CDK in the [CDK Workshop](https://cdkworkshop.com) as well as a number of community-written blog posts on the subject. As far as utilizing Codestar, we do not recommend it but do offer [resources](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-codestar-readme.html) for it in the Construct Library. It is not needed as the `pipelines` module in the CDK abstracts-out source management, so there is no requirement to build it by hand.
