### ISSUE TITLE
v2 aliasConfiguration depreciated

### ISSUE THREAD

**Issue by dbroadhurst** [aws-samples/aws-cdk-examples#491]
aliasConfiguration CloudFrontWebDistribution is depreciated in CDK v2 libs. Can't seem to find information on how to resolve it.

**Comment by ryparker** [comment]
@dbroadhurst Could you provide a link to the example pertaining to this bug?

**Comment by ryparker** [comment]
The [`Distribution`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Distribution.html) API is currently being built to replace the existing [`CloudFrontWebDistribution`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistribution.html) API. More info on that [in our docs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-cloudfront-readme.html#distribution-api)

If you'd rather keep using `CloudFrontWebDistribution` but would like to replace the use of [`aliasConfiguration`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistribution.html#aliasconfigurationspan-classapi-icon-api-icon-deprecated-titlethis-api-element-is-deprecated-its-use-is-not-recommended%EF%B8%8Fspan) then you can use the [`viewerCertificate`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistribution.html#viewercertificate) prop instead. 

E.g.

```ts
import { Certificate, CertificateValidation } from '@aws-cdk/aws-certificatemanager';
import { CloudFrontWebDistributio, ViewerCertificate, SecurityPolicyProtocol } from '@aws-cdk/aws-cloudfront';

const DOMAIN = 'mysite.com'
const CNAMES = [`www.${DOMAIN}`]

const certificate = new Certificate(scope, 'DistributionCertificate', {
	  domainName: DOMAIN,
	  subjectAlternativeNames: [...CNAMES],
	  validation: CertificateValidation.fromDns(props.hostedZoneForDomain)
});

const distribution = new CloudFrontWebDistribution(scope, 'Distribution', {
    viewerCertificate: ViewerCertificate.fromAcmCertificate(certificate, {
	      aliases: [DOMAIN, ...CNAMES],
	      securityPolicy: SecurityPolicyProtocol.TLS_V1_2_2021,
	    }
	  ),
	...
};
```

**Comment by ryparker** [comment]
Changed to guidance as this does not seem to be a bug. Feel free to respond if you believe otherwise.

**Comment by dbroadhurst** [comment]
@ryparker Thanks, I'll give the alternate a try. 

I submitted because the example wouldn't build with CDK v2 but looks like the example has now changed.
