### ISSUE TITLE
SFTP Over the Internet with Custom IdP(Multiple AD authentication without Using AWS Directory Service)

### ISSUE THREAD

**Issue by sanjeevim** [aws-samples/aws-cdk-examples#494]
## :rocket: Feature Request
Hello AWS,

Good Morning!

I would like to contribute the solution that we deployed for SFTP with Self-Managed Custom AD(IdP) over the internet with multiple Security Parameter with NLB,WAF,SG,IAM Policy, S3 Bucket Policy and Local Network Firewall.

![image](https://user-images.githubusercontent.com/3786325/131357673-15b7a662-0295-4c9c-a76b-3959d568c2eb.png)

Requesting you to provide the necessary privilege to contribute the code to aws-example
 repository.

Thanks,
Sanjeevi Mahalingam
 
### General Information

* [x] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Environment

  - **CDK CLI Version:** 
  - **Example:** 
  - **Example Version:** 
  - **OS:** 
  - **Language:**

**Comment by sanjeevim** [comment]
Requesting you to provide the necessary privilege to contribute the code to aws-example
repository.

**Comment by skinny85** [comment]
@sanjeevim this is a public repository - you can contribute to it through a Pull Request without any additional privileges.

**Comment by ryparker** [comment]
Hey @sanjeevim 👋🏻 

As mentioned above you should be able to fork this repository, commit changes, then open a pull request for this repository. Check out our [contributing document](https://github.com/aws-samples/aws-cdk-examples/blob/81a63190e9bbd538cb6e9a66a727e7cd70b1a8d3/CONTRIBUTING.md) for useful information such as how to [fork a github repo](https://help.github.com/articles/fork-a-repo/).

I'm labeling this issue as p2 which means that we are unable to work on this immediately. We use +1s to help us prioritize our work, and as always we are happy to take contributions.
