### ISSUE TITLE
Outdated Instructions for CDK Step Function Python Example

### ISSUE THREAD

**Issue by navneethc** [aws-samples/aws-cdk-examples#500]
### What is the problem?
The [Step Function Python CDK example](https://github.com/aws-samples/aws-cdk-examples/blob/190b4251e20035c44afe5cc601ed7d92e598be00/python/stepfunctions/stepfunctions/stepfunctions_stack.py) uses the Task class, which according to the [API documentation](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_stepfunctions/Task.html) is deprecated. Would appreciate an updated non-trivial example that uses all the important classes.

### Reproduction Steps
N/A

### Verbose Log
N/A

### Environment

  - **CDK CLI Version:** 1.120.0 (build 6c15150)
  - **Example:** N/A
  - **Example Version:** N/A
  - **OS:** Ubuntu 20.04
  - **Language:** Python

### Other information 
N/A

**Comment by ryparker** [comment]
Hey 👋🏻 

Thanks for bringing this to our attention @navneethc.

I labeled this as p1 which means it has been prioritized as important, although please keep in mind that we do have a large number of issues at the moment. It may be some time before we are able to solve this particular issue. We use +1s to help us prioritize our work, and as always we are happy to take contributions if anyone is interested to pick this up and submit a PR.

**Comment by navneethc** [comment]
Hi @ryparker, thanks for the response. I believe there's already been a PR (#502) for this issue.

**Comment by ryparker** [comment]
Closing after PR was merged: https://github.com/aws-samples/aws-cdk-examples/pull/502
