### ISSUE TITLE
aws_cdk.pipelines.CdkStage: expose Role Property

### ISSUE THREAD

**Issue by github4es** [aws-samples/aws-cdk-examples#527]
### General Information

I need to add cross-account role assume permissions to the role that my Pipeline Stage creates. My stage definition is below.  My pipeline runs on one aws account and my integration tests will run against a separate aws account. 

```python
pipeline.stage(stage_name="integration_tests").add_action(
    action=pipelines.ShellScriptAction(
        action_name="RunIntegrationTests",
        commands=[
            "python -m pytest -vv tests/integration"
        ],
        additional_artifacts=[source_artifact],
        **build_defaults
    )
)
```

### Proposed Solution

would be great if I had `pipeline.stage.add_to_policy` construct where I could define an IAM policy.

It would also be great if the pipeline or stage exposed a role that we could add a polity to like

`pipeline.role.add_to_policy()` or `pipeline.stage.role.add_to_policy`

### Language

Python

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by rix0rrr** [comment]
Switch to using `CodeBuildStep`: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.pipelines/README.html#customizing-codebuild-projects
