### ISSUE TITLE
CDK example for Stackset Deployer to OUs using Python

### ISSUE THREAD

**Issue by mittalgv** [aws-samples/aws-cdk-examples#528]
### General Information

A CDK python construct to build a stackset and deploy it different OUs.

### Proposed Solution

Going to build a sample resource and deploy it to a list of OUs (supplied via a config file). The stackset deployer will synth the CDK resource and  deploy it to OUs by reading the information from a config file via Stackset.

### Language

Python

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by ruchirshetye-aws** [comment]
We are working on this FR

**Comment by kaiz-io** [comment]
No motion on this close for staleness
