### ISSUE TITLE
cicd-pipeline example proposal

### ISSUE THREAD

**Issue by mf523** [aws-samples/aws-cdk-examples#536]
Leveraging CDK to create aws managed CICD pipeline automatically.

* Allowing creating CICD pipeline with managed service CodeCommit/CodeBuild/CodePipeline easily and quickly.
* Allowing CICD pipeline definition and service as code.
* Advocating CDK and managed CICD pipeline

**Comment by kaizio** [comment]
We have [Continuous integration and delivery (CI/CD) using CDK Pipelines](https://docs.aws.amazon.com/cdk/v2/guide/cdk_pipeline.html). Are you looking for something different? Will close soon if not.
