### ISSUE TITLE
python/new-vpc-alb-asg-mysql : rds subnet groups are not assigned to the DB subnet

### ISSUE THREAD

**Issue by DaveB93** [aws-samples/aws-cdk-examples#539]
### What is the problem?

In the python example new-vpc-alb-asg-mysql example, the RDS is created in the wrong subnets. 

https://github.com/aws-samples/aws-cdk-examples/blob/64c1512ac78dfd3f5ddabb5426a9962dbc11be15/python/new-vpc-alb-asg-mysql/cdk_vpc_ec2/cdk_rds_stack.py#L39

it should have a line like so
`                                             vpc_subnets=ec2.SubnetSelection(subnet_group_name="DB"),`

### Reproduction Steps

deploy the stack

### What did you expect to happen?

I expected the DB subnet groups to be created in the DB subnets, and was looking at the example to figure out how it could possibly work, so I deployed the stack just to see what happened, when it didn't work I tried to figure out why

### What actually happened?

DB subnets were created in the private subnets instead of the ISOLATED subnets per the documentation here
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_rds/DatabaseInstance.html  which says that it would default to PRIVATE

### CDK CLI Version

1.125.0

### Node.js Version

NA

### OS

ubuntu

### Language

Python

### Language Version

3.7.3

**Comment by ryparker** [comment]
Hey @DaveB93 👋🏻 

Thanks for bringing this to our attention.

PR here: https://github.com/aws-samples/aws-cdk-examples/pull/566
