### ISSUE TITLE
python: automated log validations for cloudtrail logs using lambda. 

### ISSUE THREAD

**Issue by 12Manoz** [aws-samples/aws-cdk-examples#540]
### General Information

Cloud trail logs can be validated using api calls, when log validation is enabled. 

Lambda can be used to automate this process for auditing and integrity of logs validation purpose to avoid and notify if cloudtrail logs has been compromised or accidentally changed. 

This is valuable for customer to achieve compliance for integrity of api call logs especially with financial and life sciences industry.

### Proposed Solution

CDK sample will 
1. Enable Cloud trail logs
2. Enable validation and store in S3 bucket
3. Use lambda to automate api calls to cloudtrail to validate and store the status in Dynamo DB. Lambda will be triggered periodically using CloudWatch corn jobs. 
4. Send notification using SNS when validation fails. 

### Language

Python

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
Thank you for the request. If you'd like to submit a sample, please feel free to do so and open a PR referencing this issue.

**Comment by 12Manoz** [comment]
Sure I would submit pr
