### ISSUE TITLE
OpenAPI document driven RestAPI Design in AWS CDK for Python/Typescript/C#

### ISSUE THREAD

**Issue by aws-josterm** [aws-samples/aws-cdk-examples#542]
### General Information

An API Gateway/Lambda Rest API is created in a stack using an OpenAPI definition file to define the API methods. This will include API Gateway request validators and Integration within the definition file. It will eliminate the need to define the API methods in the stack file. Example code will be available in Typescript and Python.

### Proposed Solution

This solution provides sample code to the user that sets up a basic Lambda function, defines the OpenAPI definition file as an Asset API Definition an adds this definition to an API Gateway Instance.  

### Language

Typescript, Python, C#

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
There's a few ways I can read this:

* This functionality exists already in the existing constructs and you'd like an example of this being done
* You'd like an example of building a construct which does this
* You'd like API Gateway (the underlying service) to consume OpenAPI schemas and glue the right things together.

**Comment by bilalmughal** [comment]
I can write a comprehensive example that usess OpenAPI specification and uses lambda authorizer. If there is an interest I can send a pull request.
