### ISSUE TITLE
Neptune: Add CDK example for setting up a Neptune cluster with a SageMaker Notebook workbench associated to it

### ISSUE THREAD

**Issue by vinodabh** [aws-samples/aws-cdk-examples#552]
### General Information

Graph databases are very popular now, because the barrier-to-entry has been lowered by new offerings like Amazon Neptune. Amazon Neptune is a fully managed graph database that integrates well with other AWS services. Typically a SageMaker Notebook workbench configured with a specific lifecycle configuration is used to interact with the graph database. A CDK example of how to set up Neptune with the Notebook workbench would be useful for anyone working with Amazon Neptune.

### Proposed Solution

The CDK example would set up the following components to achieve this solution

- VPC with subnet and security group
- Neptune Cluster with cluster and db parameters
- Notebook with an IAM role, custom lifecycle and network association

### Language

Typescript, Python, .NET

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
There is currently a similar demonstration over in the [AWS Blog](https://aws.amazon.com/blogs/database/analyze-amazon-neptune-graphs-using-amazon-sagemaker-jupyter-notebooks/), if I understand the request.

**Comment by vinodabh** [comment]
This request was for a CDK example. I have already merged a pull request with the CDK example. I will close this issue.

**Comment by vinodabh** [comment]
This sample is available here: https://github.com/aws-samples/amazon-neptune-samples/tree/master/neptune-sagemaker/cdk/python/neptune-notebook
