### ISSUE TITLE
AWS Transfer Family: CDK example to create a fully managed SFTP server to transfer files directly into and out of Amazon S3

### ISSUE THREAD

**Issue by vinodabh** [aws-samples/aws-cdk-examples#553]
### General Information

The AWS Transfer Family offers fully managed support for the transfer of files over SFTP, FTPS, and FTP directly into and out of Amazon S3 or Amazon EFS. Let's create a CDK example of how to configure an SFTP server using AWS Transfer Family

### Proposed Solution

The CDK solution will spin up the following components:

- Transfer Family SFTP server
- S3 bucket
- IAM role and policy
- Username and Password stored in Secrets Manager

### Language

Typescript, Python, .NET

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
Thank you for the suggestion, and sorry for taking so long! 

If you'd like, we graciously accept PRs that demonstrate such things.
