### ISSUE TITLE
(aws-cdk-go): static-site example

### ISSUE THREAD

**Issue by SaulMagnusson** [aws-samples/aws-cdk-examples#556]
### General Information

I've written a stable example in aws-cdk-go that launches a secure static site. The example is also present in the other languages satisfying the Language Parity requirement for examples, and also has some explanation of syntax particular to go explained in the README

### Proposed Solution

I've written the example secure-site and a README.md in this repo:

https://github.com/SaulMagnusson/aws-cdk-go-example-static-site

I'm hoping it can be pulled into the go examples section.

Please let me know of any changes I can make to improve the readability of the code or to adjust things to be better in line with best practice.

### Language

Go

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
If you'd please open a PR against this repo with the sample added, we'd be glad to take it!

**Comment by SaulMagnusson** [comment]
Thanks for the invitation to contribute. I made the pull request (my first!) here:

https://github.com/aws-samples/aws-cdk-examples/pull/688
