### ISSUE TITLE
Create CDKv2 samples

### ISSUE THREAD

**Issue by njlynch** [aws-samples/aws-cdk-examples#558]
### General Information

In advance of the CDKv2 GA launch, we should adopt a good number of samples (per language) to CDKv2.

### Proposed Solution

Convert samples!

### Language

Typescript, Python, .NET, Java, Go

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
This was done, thanks Nick!!
