### ISSUE TITLE
aws_ecs: ScalableTaskCount.scale_on_request_count functionality unnclear

### ISSUE THREAD

**Issue by dpmccabe** [aws-samples/aws-cdk-examples#567]
### Guidance Question

What is the time interval for ScalableTaskCount.scale_on_request_count?

### The Question

```py
service = ecs.FargateService(...)

capacity = service.auto_scale_task_count(min_capacity=1, max_capacity=5)

capacity.scale_on_request_count(
    id="hlink-api-autoscale-ram",
    requests_per_target=???
)
```

The [ScalableTaskCount.scale_on_request_count](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_ecs/ScalableTaskCount.html#aws_cdk.aws_ecs.ScalableTaskCount.scale_on_request_count) method requires an argument `requests_per_target` but what is the time interval being used? Per second? Per minute? I'm assuming it doesn't mean the total number of requests per target since the target was instantiated. There's no way to set this value intelligently without knowing the answer to this question.

### CDK CLI Version

1.132.0

### Language

Python

**Comment by NGL321** [comment]
Hey @dpmccabe,

Sorry for the lack of response here. To be completely honest, neither the Cloudformation documentation nor the CDK documentation make entirely clear what the count interval is, so it is safe to say that said interval is determined by the AWS Autoscaling service itself. Said [documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html) indicates that the request interval is __`1-minute`__
