### ISSUE TITLE
/python/custom-resource - requirements.txt empty

### ISSUE THREAD

**Issue by tomjones2a** [aws-samples/aws-cdk-examples#577]
### What is the problem?

Requirements.txt is empty 

### Reproduction Steps

pip install -r requirements.txt.

### What did you expect to happen?

requirements to be present and install.

### What actually happened?

Nothing is installed.

### CDK CLI Version

1.134.0

### Node.js Version

NA

### OS

Mac

### Language

Python

**Comment by NGL321** [comment]
Could you indicate where you are experiencing this? Python will resolve dependencies automatically from the imports in the `*.py` files as long as the directory is specified in the requirements file as editable `-e .`. See [here](https://pip.pypa.io/en/stable/cli/pip_install/)
