### ISSUE TITLE
PHP library support

### ISSUE THREAD

**Issue by Satheez** [aws-samples/aws-cdk-examples#581]
### Guidance Question

Amazon MQ connection parameters to be provided

### The Question

I'm trying to connect 'Amazon MQ' using PHP
But due to SSL certification error, I'm unable to connect (locally working since the SSL is turned off)

I've used the following library https://github.com/php-amqplib/php-amqplib

Can you please guild me how to provide/what are the data to be provided to 'Amazon MQ' (other than hosr, port, username, password)?

I couldn't find any other aws repo for PHP support.

### CDK CLI Version

-

### OS

Linux & Mac

### Language

Python

**Comment by NGL321** [comment]
Sorry for the delayed response on this issue. Unfortunately, we do not presently support PHP within the CDK and do not have plans to implement language support at the moment. I recommend you check out the [AWS PHP SDK](https://github.com/aws/aws-sdk-php) for interfacing with AWS services in PHP
