### ISSUE TITLE
Golang example for EC2 instance creation

### ISSUE THREAD

**Issue by sivaramsajeev** [aws-samples/aws-cdk-examples#588]
### General Information

Golang example for EC2 instance creation

### Proposed Solution

I have raised a PR with example 

### Language

Go

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by indrora** [comment]
I'm sorry this has taken so long to get to. We'll be reviewing the PR.

**Comment by kaiz-io** [comment]
Was merged
