### ISSUE TITLE
(golang): Add S3 object upload triggering lambda example

### ISSUE THREAD

**Issue by sivaramsajeev** [aws-samples/aws-cdk-examples#592]
### General Information

Add S3 upload trigger lambda example

### Proposed Solution

I have raised PR to add the example 

### Language

Go

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by kaiz-io** [comment]
Examples exists. https://github.com/aws-samples/aws-cdk-examples/tree/main/go/s3-event-processor
