### ISSUE TITLE
api-cors-lambda-crud-dynamodb TypeScript AssetCode

### ISSUE THREAD

**Issue by nmussy** [aws-samples/aws-cdk-examples#60]
I'm having a hard time understanding how the [api-cors-lambda-crud-dynamodb](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/api-cors-lambda-crud-dynamodb/) example Lambdas would execute. The `AssetCode` given to the functions are TypeScript files, and the runtime is a plain `NodeJS810`.

I've tried doing similar in with `aws-cdk@0.36.0`, but I can't figure out how these files would be compiled, they're just zipped and shipped as is.

**Comment by popovitsj** [comment]
When you do `npm run build` the typescript files are compiled to javascript.

**Comment by NGL321** [comment]
Closing due to age and answer.

😸
