### ISSUE TITLE
Deprecated aws-cdk/cdk in use

### ISSUE THREAD

**Issue by tom98784** [aws-samples/aws-cdk-examples#61]
The Python examples (I haven't looked at other languages) use the just-deprecated aws-cdk/cdk module. This has been replaced with the aws-cdk/core module (see [here](https://github.com/awslabs/aws-cdk/blob/master/CHANGELOG.md).)
The fix may well be as simple as replacing all references to aws-cdk/cdk to aws-cdk/core.

**Comment by tom98784** [comment]
https://github.com/awslabs/aws-cdk/blob/master/CHANGELOG.md

0.36.0 (2019-06-24)
...
BREAKING CHANGES
IMPORTANT: previous versions of the CDK CLI will not be fully compatible with this version of the framework and vice versa.
core: the @aws-cdk/cdk module was renamed to @aws-cdk/core, python: aws_cdk.core, java: the artifact cdk in groupId software.amazon.awscdk was renamed to core
...

**Comment by tbadlov** [comment]
I am working on a PR that addresses these issues (at least for the typescript portion).

**Comment by oren** [comment]
I am getting an error which I assume is related:
```
CDK CLI can only be used with apps created by CDK >= 0.36.0
```

project: Fargate Service with Logging. CDK version: 0.36.1 (build 1ba8a14)

**Comment by tom98784** [comment]
The PR referenced above (#62) includes changes that will bring the TS Fargate w. logging up to date with 0.36.x. They're relatively minor so it's easy to find them in the PR and apply them yourself.

**Comment by tom98784** [comment]
Saved you the searching - here's the three updated files
[typescript/ecs/ecs-service-with-logging/index.ts](https://github.com/aws-samples/aws-cdk-examples/pull/62/files#diff-b9d29a9b23ab48df049b37d33a223ce0)
[typescript/ecs/ecs-service-with-logging/package.json](https://github.com/aws-samples/aws-cdk-examples/pull/62/files#diff-2ccb53610e7214439da6d7e01c391538)
[typescript/ecs/ecs-service-with-logging/package-lock.json](https://github.com/aws-samples/aws-cdk-examples/pull/62/files#diff-2d9291caafaa33cfadd215975e784294l)

**Comment by oren** [comment]
Thank you!
