### ISSUE TITLE
(typescript): An example using EventBridge rule to schedule Lambda function

### ISSUE THREAD

**Issue by jambasil** [aws-samples/aws-cdk-examples#615]
### General Information

Provide an example for how to set up an Amazon EventBridge scheduled rule to execute an AWS Lambda function.

### Proposed Solution

Create an example for the pattern of creating a scheduled Lambda using EventBridge.

### Language

Typescript

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
If you're still able to implement this we'd be happy to review a PR

**Comment by BrandonMichaelWebb** [comment]
I will work on configuring this request for a PR
