### ISSUE TITLE
CDK DNS Firewall: DNS Firewall CDK example

### ISSUE THREAD

**Issue by askkhan84** [aws-samples/aws-cdk-examples#620]
## Overview
A CDK app for DNS firewall that is configurable through a config file to manage settings and domains. Configurable options will include logging, mode (block, alert), Cloudwatch alarms for blocked domains.
Services used:
- DNS firewall
- CloudWatch metric filters
- CloudWatch alarm

### Proposed Solution

Proposing to build a CDK app that implements DNS firewall with VPC attachment, logging and alerting

### Language

Typescript

### Acknowledge

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by peterwoodworth** [comment]
If you're still able to implement this, we'd be happy to review a PR if you submit one
