### ISSUE TITLE
forecast-pipeline

### ISSUE THREAD

**Issue by rotemuri** [aws-samples/aws-cdk-examples#622]
### Overview
A CDK app for running Amazon Forecast steps in a stepfunction pipeline. this can be connected to an app for reusability and automation of the forecast steps.

### Services used:
- Amazon Forecast
- IAM
- S3
- Lambda
- Step Function

### Language
Typescript

### Other information
No response

### Acknowledge
- [x] I may be able to implement this feature request
- [ ]  This feature might incur a breaking change

**Comment by kaiz-io** [comment]
Closing based on new about [Amazon Forecast](https://aws.amazon.com/blogs/machine-learning/transition-your-amazon-forecast-usage-to-amazon-sagemaker-canvas/)
