### ISSUE TITLE
bug(typescript/ecs): Placement group placed in wrong construct

### ISSUE THREAD

**Issue by its-mirus-lu** [aws-samples/aws-cdk-examples#636]
### What is the problem?

Identical to #628 except this is in the Typescript example.

The placement group attribute was incorrectly placed in the TaskDefinition construct instead of the ServiceDefinition construct.

Also, the stack name starts with 'aws' which could cause a naming violation when a CapacityProvider is specified.

### Reproduction Steps

1. clone the aws-cdk-examples repo
2. navigate to the [typescript/ecs/ecs-service-with-task-placement](https://github.com/aws-samples/aws-cdk-examples/tree/752df6302e534a7df22a809536c588deaf444c4d/typescript/ecs/ecs-service-with-task-placement) folder
3. call cdk deploy

### What did you expect to happen?

Successful deployment with no errors

### What actually happened?

Resource handler returned message: "Invalid request provided: Create TaskDefinition: constraint.type 'distinctInstance' is not supported. (Service: AmazonECS; Status Code: 400; Error Code: ClientException

### CDK CLI Version

2.13.0 (build b0b744d)

### Node.js Version

8.5.1

### OS

v16.14.0

### Language

Typescript

### Language Version

TypeScript 4.6.3

**Comment by peterwoodworth** [comment]
Thanks for the report, and for your patience here!
