### ISSUE TITLE
Create an example for deploying AWS Backup resources to backup AWS S3

### ISSUE THREAD

**Issue by dariusjs** [aws-samples/aws-cdk-examples#657]
### Describe the feature

Create an example for deploying AWS Backup resources to backup AWS S3.

Currently AWS S3 is not natively supported through constructs for AWS Backup. When using resource tags on S3 buckets can be scheduled for backup though.

### Use Case

A clear example of what is required to have S3 backups working using AWS Backup.

### Proposed Solution

I will create a pull request which shows tags added to an S3 bucket and AWS Backup targetting these tags.

### Acknowledgements

- [X] I may be able to implement this feature request
- [x] This feature might incur a breaking change

### Language

Typescript

**Comment by dariusjs** [comment]
I've added the example pull request
https://github.com/aws-samples/aws-cdk-examples/pull/658

**Comment by dariusjs** [comment]
#662 https://github.com/aws-samples/aws-cdk-examples/pull/658

**Comment by dariusjs** [comment]
#662

**Comment by peterwoodworth** [comment]
Thanks a bunch for the PR @dariusjs, we'll have a look hopefully in the next couple weeks

**Comment by dariusjs** [comment]
I've ugpraded typescript to 4.6 as this was still using typescript 3.9 which caused build issues.
