### ISSUE TITLE
Reusable construct to create Backup Plan

### ISSUE THREAD

**Issue by spac3-monk3y** [aws-samples/aws-cdk-examples#668]
### Describe the feature

Create an easy to use reusable CDK construct to abstract the creation of AWS Backup resources to backup supported services such as RDS, EC2, etc. 

### Use Case

Reduce boilerplate code in projects with resources that require different backup policies due to compliance.

### Proposed Solution

Provide a CDK construct that allows basic configuration and receive a list of resources to apply the backup plan to.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Typescript

**Comment by indrora** [comment]
Thank you for the suggestion (And the PR!) 

This sort of construct would be best featured in the Construct Hub: https://constructs.dev/

**Comment by spac3-monk3y** [comment]
> Thank you for the suggestion (And the PR!)
> 
> This sort of construct would be best featured in the Construct Hub: https://constructs.dev/

Saw a few constructs in this repo thought it was relevant.
