### ISSUE TITLE
python/image-content-search module does not deploy

### ISSUE THREAD

**Issue by samtwil** [aws-samples/aws-cdk-examples#681]
### Describe the bug

When running `cdk deploy` from the `python/image-content-search` directory on a fresh AWS account, I get an error indicating `Domain already associated with another user pool.`

### Expected Behavior

The CDK stack should deploy successfully

### Current Behavior

Here is the error output I see when executing `cdk deploy`:

```
ImageContentSearch: creating CloudFormation changeset...
5:45:29 PM | CREATE_FAILED        | AWS::Cognito::UserPoolDomain                | ICSUSERSPOOLDOMAINFF1CF72E
Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: In
validParameterException; Request ID: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX; Proxy: null)
```

### Reproduction Steps

1. Clone latest version of aws-cdk-samples
2. Navigate to `python/image-content-search`
3. Run `cdk deploy`

### CDK CLI Version

2.19.0 (build e0d3e62)

### Node.js Version

v16.14.2

### OS

macOs Monterrey Version 12.3.1

### Language

Python

### Language Version

Python (3.8.9)

**Comment by NGL321** [comment]
I have reproduced this and confirmed the behavior, looks like @indrora is going to look into resolution

**Comment by indrora** [comment]
Touching this old sample, yeah this is a problem :/

**Comment by indrora** [comment]
I've figured out something that might be a bug in the CDK but might also just be a documentation failure: Domain prefixes are globally unique, like S3 bucket names. 

if you set `Cognito.DomainPrefix` in config.yml to something else, the deploy works fine. If you don't, because the stack has been deployed by *someone else*, you get this error.
