### ISSUE TITLE
Missing dependencies in appsync-graphql-dynamodb example

### ISSUE THREAD

**Issue by samputer** [aws-samples/aws-cdk-examples#698]
### Describe the bug

Cannot tear down `appsync-graphql-dynamodb` due to missing dependencies on datasource.

### Expected Behavior

Should be able to destroy stack when running `cdk destroy`

### Current Behavior

`cdk destroy` yields the following error

```
16:24:39 | DELETE_FAILED        | AWS::AppSync::DataSource    | ItemsDataSource
Resolver for type Mutation and field delete associated with data source (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: ...
```

### Reproduction Steps

In the `typescript/appsync-graphql-dynamodb` directory:

`cdk deploy`

followed by

`cdk destroy`

Observe error

### Possible Solution

Add missing dependencies to all of the datasources. PR inbound.

### CDK CLI Version

2.31.0 (build b67950d)

### Node.js Version

v16.13.1

### OS

MacOS 12.4

### Language

Typescript

**Comment by samputer** [comment]
PR raised: https://github.com/aws-samples/aws-cdk-examples/pull/699

**Comment by awscamille** [comment]
I think #1005 addresses that issue.

**Comment by kaizio** [comment]
Confirmed one is able to `cdk deploy` and `cdk destroy`.
