### ISSUE TITLE
(feat) : Add an example to launch OpenSearch Service with CDK 

### ISSUE THREAD

**Issue by prashanttct07** [aws-samples/aws-cdk-examples#706]
### Describe the feature

Amazon OpenSearch Service is being used by multiple customer and users to store log and catalogue data to run real time analytics or website search. 

As of now, there is no good sample to launch the Amazon OpenSearch Service stack using CDK. And with this I would like to contribute the sample for OpenSearch Service. 

### Use Case

To add support for OpenSearch Service using CDK

### Proposed Solution

I have in house sample which launches the stack for OpenSearch Service, I will work on and add the PR if idea is approved. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by peterwoodworth** [comment]
Do you have any proposals on what sort of infrastructure you would build? We will want to do a bit more than create just an OpenSearch Service to meet the standards of this repo.

**Comment by prashanttct07** [comment]
@peterwoodworth 
I was following couple of examples under this repo like: https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ec2/instance

So, my initial thought is to use CDK to:
1) Launch an Amazon OpenSearch Service Domain 
2) Launch an EC2 instance and install nginx as proxy to access OpenSearch Dashboards 
3) Use user data commands from EC2 instances to setup some features in OpenSearch such as alerting, ISM, User and Role, dashboard import etc. 

Let me know if this is good as part of flow, if not what else you would like to see this to maintain the standard.

**Comment by peterwoodworth** [comment]
This sounds excellent @prashanttct07 🙂 Go for it!

**Comment by prashanttct07** [comment]
@peterwoodworth I have worked on the sample and below is the PR for same: https://github.com/aws-samples/aws-cdk-examples/pull/709

I have tested it by deploying myself, but not sure if there is any process for testing before it gets merged.

**Comment by prashanttct07** [comment]
Hello team, 
ANy update on this?
