### ISSUE TITLE
feat(go): adding more cdk v2 examples to go section

### ISSUE THREAD

**Issue by fynnfluegge** [aws-samples/aws-cdk-examples#707]
**🚀 Feature Request**
-----------------------
### Describe the feature

**Description**
The go section has lack of examples. I would appreciate more go examples provided here.

**Environment**
CDK CLI Version: 2.3.0 (build beaa5b2)
Language: go 1.16
OS: all

### Use Case

Since go has become popular with lambda function, it would be very helpful to provide some common cdk v2 go templates.

### Proposed Solution

**I can provide a PR with the following cdk v2 examples using go:**
- http-api &rarr; lambda-handler
- sqs &rarr; lambda-handler
- eventbridge &rarr; sqs &rarr; lambda-handler
- lambda-handler &rarr; dynamodb
- http-api &rarr;  lambda-handler protected with jwt authorizer using cognito as identity provider
- http-api &rarr;  eventbridge integration protected with jwt authorizer using cognito as identity provider
- static-website using S3, CloudFront, Certificate Manager and Route53

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Go

**Comment by peterwoodworth** [comment]
Thanks for the feature request, I agree we need more Go examples! Let me know once you've linked a PR and we'll try to review it

**Comment by fynnfluegge** [comment]
Alright, I will do so soon!

**Comment by fynnfluegge** [comment]
@peterwoodworth Hey, I created a PR with nine go examples #721

**Comment by peterwoodworth** [comment]
Thanks @fynnfluegge, I'll try to review sooner rather than later 🙂

**Comment by fynnfluegge** [comment]
Hey @peterwoodworth , thank you! I just saw that the third build check has failed, it seems the cause is the s3-website example. I will fix this as soon as I can.

**Comment by fynnfluegge** [comment]
Hey @peterwoodworth, I fixed the build checks in #721
