### ISSUE TITLE
Python Lambda From Container ARN error

### ISSUE THREAD

**Issue by jonathan-eckel** [aws-samples/aws-cdk-examples#715]
### Describe the bug

Setting `use_pre_existing_image = True` causes the cdk synth process to fail.

> jsii.errors.JSIIError: The `resource` component (6th component) of an ARN is required: arn:aws:ecr:${Token[AWS.Region.7]}:${Token[AWS.AccountId.3]}

### Expected Behavior

The cdk synth process should finish successfully.

### Current Behavior

Setting `use_pre_existing_image = True` causes the cdk synth process to fail.

> jsii.errors.JSIIError: The `resource` component (6th component) of an ARN is required: arn:aws:ecr:${Token[AWS.Region.7]}:${Token[AWS.AccountId.3]}

### Reproduction Steps

Set `use_pre_existing_image = True` in the app.py in the `python/lambda-from-container` example

### Possible Solution

Adding the resource component to the ARN string should resolve this issue.

### CDK CLI Version

2.37.1 (build f15dee0)

### Node.js Version

v18.7.0

### OS

Mac OSX

### Language

Python

### Language Version

Python 3.8.9

**Comment by peterwoodworth** [comment]
Left a comment on the PR 🙂
