### ISSUE TITLE
Failing tests in Java build

### ISSUE THREAD

**Issue by ryparker** [aws-samples/aws-cdk-examples#723]
### Describe the bug

Currently our automated build canary is failing due to a failing Java test.

```
Running com.amazonaws.cdk.examples.ECSFargateLoadBalancedStackTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.91 sec <<< FAILURE!
testStack(com.amazonaws.cdk.examples.ECSFargateLoadBalancedStackTest)  Time elapsed: 3.868 sec  <<< FAILURE!
```

This was reported in an auto-cut SIM: V694428904

### Expected Behavior

All tests passing in the main branch.

### Current Behavior

Failing Java tests in the main branch.

### Reproduction Steps

Run `./scripts/build-java.sh` from root of main branch.

### CDK CLI Version

2.38.1

### Node.js Version

16.17.0

### OS

macOS Monterey

### Language

Java

**Comment by peterwoodworth** [comment]
Yup, the expected template differs from the actual template
