### ISSUE TITLE
https://github.com/aws-samples/aws-cdk-examples/tree/master/java/custom-resource fails to run

### ISSUE THREAD

**Issue by nagkumar** [aws-samples/aws-cdk-examples#748]
### Describe the bug

https://github.com/aws-samples/aws-cdk-examples/tree/master/java/custom-resource  is not working at per readme.md instructutions

### Expected Behavior

cdk ls should work properly

### Current Behavior

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project py-lambda: An exception occurred while executing the Java class. Error: cannot find ./lambda/custom-resource-handler.py/index.js
[ERROR] @jsii/kernel.RuntimeError: Error: cannot find ./lambda/custom-resource-handler.py/index.js
[ERROR]     at Kernel._ensureSync (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime16483806039836653505\lib\program.js:7889:27)
[ERROR]     at Kernel.sinvoke (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime16483806039836653505\lib\program.js:7325:34)
[ERROR]     at KernelHost.processRequest (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime16483806039836653505\lib\program.js:10466:36)
[ERROR]     at KernelHost.run (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime16483806039836653505\lib\program.js:10429:22)
[ERROR]     at Immediate._onImmediate (C:\Users\RAJANA~1\AppData\Local\Temp\jsii-java-runtime16483806039836653505\lib\program.js:10430:46)
[ERROR]     at process.processImmediate (node:internal/timers:471:21)

### Reproduction Steps

run 

cdk ls

### CDK CLI Version

2.43.1 (build c1ebb85)

### Node.js Version

18

### OS

windows 10

### Language

Java

### Language Version

18

**Comment by its-mirus-lu** [comment]
The java/custom-resource example should be deleted/deprecated since the [CustomResourceProvider](https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-cloudformation.CustomResourceProvider.html) is deprecated as of v2.
