### ISSUE TITLE
ReadMe.md should explain testcases 

### ISSUE THREAD

**Issue by nagkumar** [aws-samples/aws-cdk-examples#750]
### Describe the bug

few of the examples here have test cases... however readme.md does not say, when and how to run the test cases,

better, readme.md explain the test cases, if they have to be run after deployment or even without deploy  etc..

some few liners to explain test approach would help 

### Expected Behavior

explain the test cases

### Current Behavior

no explanation of the test cases

mvn package does invoke test, but how is that related to real time testing of actual infra in cloud is not clear

### Reproduction Steps

check readme.md

### Possible Solution

better explanation of steps to test

### CDK CLI Version

2.43.1 (build c1ebb85)

### Node.js Version

18

### OS

win10

### Language

Java

### Language Version

18

**Comment by peterwoodworth** [comment]
Can you please describe the list of examples affected by this?
