### ISSUE TITLE
WAF example for Java

### ISSUE THREAD

**Issue by evermbr** [aws-samples/aws-cdk-examples#757]
### Describe the feature

For language parity, there should be an example written in Java for creating a WAF

### Use Case

Developers who are utilizing CDK w/ Java

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Java

**Comment by peterwoodworth** [comment]
Thanks for the request @evermbr,

We should be able to convert [this example](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/waf) to Java

I'm marking this as p2, which means we won't be able to get to this ourselves. If anyone wants to contribute this, please open a PR and we will try our best to get to it. Thanks!

**Comment by evermbr** [comment]
I have created a PR with corresponding changes [here](https://github.com/aws-samples/aws-cdk-examples/pull/758), if someone would like to review and approve
