### ISSUE TITLE
New Pattern/ Example Idea: EC2 with SSH Access to EMR Cluster

### ISSUE THREAD

**Issue by tommywhelan** [aws-samples/aws-cdk-examples#765]
### Describe the feature

I am thinking of making a pattern that spins up a basic EMR cluster, with an accompanying EC2 Instance that has SSH access to the cluster, for secure access.

### Use Case

Frequently, I will spin up an EMR cluster to test something out, but it often takes a while to actually set up the SSH access so that I can appropriately use the cluster. 

With this pattern, EMR developers will quickly be able to spin up their EMR cluster and have access to it in order to test out functionality and develop on EMR.

### Proposed Solution

I made this rough diagram/ sketch to show what the eventual implementation might look like...

![emr_cdk](https://user-images.githubusercontent.com/97986883/198090761-356c49b6-fbbc-4e5b-944b-80e29f57cfd7.png)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by tommywhelan** [comment]
Just following up!

Does this seem to be a valid pattern that would be of use for the repo?

**Comment by tommywhelan** [comment]
I have already developed the code for this pattern, and could easily it include it in this repo (with some checks of course)...

Is there anyone I can speak to/ communicate this with??

**Comment by kaizio** [comment]
Yes this would be a good example for this repo.

**Comment by tommywhelan** [comment]
@kaizio What would be the next steps? Should I make a PR my new pattern?
