### ISSUE TITLE
Analyze data in S3 with Athena and Glue

### ISSUE THREAD

**Issue by micahwalter** [aws-samples/aws-cdk-examples#766]
### Describe the feature

I'd like to propose a sample CDK application that automatically provisions and configures Amazon Athena to be able to query data stored in an S3 bucket. This would include an AWS Glue Crawler and Data Catalog to create the tables for Athena.

### Use Case

Amazon Athena is a powerful and easy to use tool for querying data on S3. Data engineers will likely want a simple IaaC pattern for setting up Athena, connecting it to an S3 bucket, and configuring a Glue Crawler as a starting point for analyzing data on AWS.

### Proposed Solution

This is a pretty straightforward CDK example. I would also like to add integration with KMS for data encryption, and would suggest providing a small sample dataset. The proposed solution would create an S3 bucket, upload the sample data, configure a Glue Crawler and establish the connection to Athena.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by micahwalter** [comment]
Is there interest in this?

**Comment by paulosergio-jnr** [comment]
Hi @micahwalter. 

I can take this one.
