### ISSUE TITLE
CDK Example: New VPC in a AWS Local Zone with public and private subnet

### ISSUE THREAD

**Issue by rigorighetti** [aws-samples/aws-cdk-examples#771]
### Describe the feature

I'm proposing to create an example to show how you could deploy the network infrastructure needed to start using an AWS Local Zone. The example will create a new VPC with a public subnet with an Internet Gateway in the associated route table and a private subnet with a NAT EC2 instance as default gateway in the route table associated with the private subnet (please keep in mind that at the moment NAT gateway in Local Zones is not supported). The NAT instance will be managed by an AutoScaling group that will ensure the health status of the instance. The example will inherently show also how you can deploy an EC2 instance, managed by AutoScaling, in a AWS Local Zone.

### Use Case

When I started working with AWS Local Zones, I noticed that there are no good examples that show how you can deploy resources in a AWS Local Zone through CDK. 

### Proposed Solution

To use an AWS Local Zone you need to explicitly define the Availability Zone where you want to create the VPC subnets passing the name of the Local Zone you want to use.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Python

**Comment by markusl** [comment]
A TypeScript example of using LocalZones is also available https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ec2-ssm-local-zone
