### ISSUE TITLE
Build of s3-object-lambda fails

### ISSUE THREAD

**Issue by markusl** [aws-samples/aws-cdk-examples#787]
### Describe the bug

Build of s3-object-lambda fails: ```lib/s3-object-lambda-stack.ts:92:15 - error TS2322: Type '{ AwsLambda: { FunctionArn: string; }; }' is not assignable to type 'IResolvable | ContentTransformationProperty'. Object literal may only specify known properties, and ''AwsLambda'' does not exist in type 'IResolvable | ContentTransformationProperty'.```

This seems to be caused by casing changes in the underlying library: AwsLambda -> awsLambda.

### Expected Behavior

Build should not fail.

### Current Behavior

Build fails.

### Reproduction Steps

Run a build

### CDK CLI Version

latest

### Node.js Version

all

### OS

all

### Language

Typescript

**Comment by peterwoodworth** [comment]
This is due to a regression in CDK package, once the new version releases this should fix itself
