### ISSUE TITLE
typescript/appsync-graphql-dynamodb doesn't deploy

### ISSUE THREAD

**Issue by yyolk** [aws-samples/aws-cdk-examples#79]
I've encountered several issues trying to build the typescript/appsync-graphql-dynamodb example

my first stab at issues encountered are with #78 

First issues are, managed policy name is invalid:

```
1/12 | 10:55:37 AM | CREATE_FAILED        | AWS::IAM::Role              | ItemsDynamoDBRole (ItemsDynamoDBRole7D2E3F6D) ARN arn:aws:iam::aws:policy/arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess is not valid. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: InvalidInput; Request ID: fcceddf5-a718-11e9-af4c-c54d1a8d020e)
	new Role (/Users/yolk/code/arturo/aws-samples/aws-cdk-examples/typescript/appsync-graphql-dynamodb/node_modules/@aws-cdk/aws-iam/lib/role.js:30:22)
	\_ new AppSyncCdkStack (/Users/yolk/code/arturo/aws-samples/aws-cdk-examples/typescript/appsync-graphql-dynamodb/index.js:50:32)
	\_ Object.<anonymous> (/Users/yolk/code/arturo/aws-samples/aws-cdk-examples/typescript/appsync-graphql-dynamodb/index.js:130:1)
	\_ Module._compile (internal/modules/cjs/loader.js:776:30)
	\_ Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
	\_ Module.load (internal/modules/cjs/loader.js:643:32)
	\_ Function.Module._load (internal/modules/cjs/loader.js:556:12)
	\_ Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
	\_ internal/main/run_main_module.js:17:11
```

next, it fails to create any of the Query's because a reference in `ApiSchema` to the `itemsTable` exists through locals, but due to the stand-up-order, an `addDependsOn` is required for it to stand up without failure. (At least that's been my experience).. see #78

**Comment by rhboyd** [comment]
Here's the fix for the DynamoDB Role.

https://github.com/aws-samples/aws-cdk-examples/pull/86/commits/83e181e6806db4097b50b3ab4377874e88336acd

**Comment by NGL321** [comment]
Hi! I was wondering if you were still experiencing this issue? I just tried to reproduce, and the example built fine for me.

If this is no longer applicable, I would love to close out this issue and the workaround PR!

TIA!
😸

**Comment by rhboyd** [comment]
It should be fixed, my PR was merged on 17-Sep with the fix.
