### ISSUE TITLE
Build App Mesh with ECS on Fargate tasks using AWS CDK

### ISSUE THREAD

**Issue by madrian** [aws-samples/aws-cdk-examples#800]
### Describe the feature

Provide CDK example of building an App Mesh on microservices running on ECS Fargate.

### Use Case

The example can accelerate adoption of App Mesh if there are CDK examples of it that can simplify its implementation.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Java

**Comment by ColinGilbert** [comment]
Would really like to see this happen, as I've been pulling hairs over this problem.

**Comment by kaiz-io** [comment]
Closing this out based on the update about [AWS App Mesh](https://aws.amazon.com/blogs/containers/migrating-from-aws-app-mesh-to-amazon-ecs-service-connect/).
