### ISSUE TITLE
Invalid principal in policy

### ISSUE THREAD

**Issue by jakiestfu** [aws-samples/aws-cdk-examples#801]
### Describe the bug

I'm trying to run the following typescript example but am receiving a failure error: https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/ec2-instance

### Expected Behavior

A simple ec2 stack to be created

### Current Behavior

`cdk deploy` fails with the following error:

```
❌  ExampleEC2Stack failed: Error: The stack named ExampleEC2Stack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Invalid principal in policy: "SERVICE":"amazonaws.com" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: <REDACTED>; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/redacted/code/example-ec2-stack/node_modules/aws-cdk/lib/index.js:327:10235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack2 (/Users/redacted/code/example-ec2-stack/node_modules/aws-cdk/lib/index.js:330:144797)
    at async /Users/redacted/code/example-ec2-stack/node_modules/aws-cdk/lib/index.js:330:130251
    at async run (/Users/redacted/code/example-ec2-stack/node_modules/aws-cdk/lib/index.js:330:128257)
```

### Reproduction Steps

```
$ npm install -g aws-cdk
$ cdk bootstrap
$ npm run build
$ cdk deploy
```

### Additional Information/Context

Perhaps it has to do with the role being incorrect? I'm pretty new to the aws cdk.

My code does nothing different than the example except I've destructured some imports.

```
const role = new Role(this, roleId, {
  assumedBy: new ServicePrincipal('amazonaws.com'),
})
```

### CDK CLI Version

2.64.0 (build fb67c77)

### Node.js Version

v16.18.0

### OS

Mac OS

### Language

Typescript

**Comment by liyanone** [comment]
@jakiestfu can you please paste here the code that you have made some changes? The ServicePrincipal that you showed

**Comment by liyanone** [comment]
@jakiestfu the ServicePrincipal that you pasted above is amazonaws.com which seems not correct. for EC2, you need to use ec2.amazonaws.com. That might be the reason that you got Invalid principal in policy error.

**Comment by liyanone** [comment]
Able to reproduce the issue by change the ServicePrincipal config from 'ec2.amazonaws.com' to 'amazonaws.com' in lib/ec2-cdk-stack.js and lib/ec2-cdk-stack.ts

**Comment by peterwoodworth** [comment]
This seems to have been manually modified from the example. @liyanone is correct about the service principal
