### ISSUE TITLE
Extending existing examples to Golang

### ISSUE THREAD

**Issue by nrajb** [aws-samples/aws-cdk-examples#802]
### Describe the feature

Currently https://docs.aws.amazon.com/cdk/v2/guide/serverless_example.html provides code example is several languages, this FR is to propose same example in golang.  

### Use Case

Will be useful to have examples in Golang for AWS CDK for those interested.

### Proposed Solution

Raised PR: https://github.com/awsdocs/aws-cdk-guide/pull/440 
With issue: https://github.com/awsdocs/aws-cdk-guide/issues/439

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Language

Go

**Comment by micahwalter** [comment]
I'd be happy to help contribute to this effort.

**Comment by kaiz-io** [comment]
Go is in the code now for the link that you provided.
