### ISSUE TITLE
Typescript rds deployments are failing with invalid parameter group

### ISSUE THREAD

**Issue by bhargaje** [aws-samples/aws-cdk-examples#825]
### Describe the bug

When trying to deploy CDK typescript RDS MySQL example getting the below error on DB Parameter group creation.

Resource handler returned message: "Invalid / Unmodifiable / Unsupported DB Parameter: open_cursors" (RequestToken: 7ab6eb2a-5
d03-a7f6-88be-ef3c666b6184, HandlerErrorCode: InvalidRequest)

### Expected Behavior

Ideal expectation is Stack should gets deployed when the region and subnet's are updated.

### Current Behavior

Stack failing with error mentioned above.

### Reproduction Steps

$ npm install -g aws-cdk
$ cd typescript/EXAMPLE_DIRECTORY (rds/mysql dir in this case)
$ npm install
$ cdk deploy

### CDK CLI Version

2.69.0 (build 60a5b2a)

### Node.js Version

v16.19.1

### OS

Amazon Linux 2

### Language

Typescript

**Comment by markusl** [comment]
Is this still an issue?

**Comment by bhargaje** [comment]
@markusl no the changes are merged, I'm closing this.
