### ISSUE TITLE
Sam build fails with Python 3.7 for example dynamodb-lambda

### ISSUE THREAD

**Issue by siddjoshi** [aws-samples/aws-cdk-examples#834]
### Describe the bug

Sam build fails while building the project, as there is hard coded dependency of PYTHON_36 runtime in dynamodb_lambda_stack.py file. 

Documentation also does not mention this hard coded dependency. 

### Expected Behavior

Either the documentation should be updated to use Python 3.6 or there should be dynamic python runtime should be choosen for lambda functions. 

### Current Behavior

Currently build fails with python 3.7, unless the runtime version is changed in dynamodb_lambda_stack.py. 

### Reproduction Steps

1. download https://github.com/aws-samples/aws-cdk-examples/tree/master/python/dynamodb-lambda
2. cd dynamodb-lambda
3. python -m virtualenv   (Use python 3.7)
4. source .venv/bin/activate
5. python -m pip install -r requirements.txt
6. cdk synth
7. sam build --template-file ./cdk.out/dynamodb-lambda.template.json

### CDK CLI Version

2.69

### Node.js Version

v16.19.1

### OS

Linux

### Language

Python

**Comment by ericzbeard** [comment]
Ideally we would migrate these to a more recent Python version. 3.7 is already EOL.
