### ISSUE TITLE
Add back key pair creation for EC2

### ISSUE THREAD

**Issue by thvasilo** [aws-samples/aws-cdk-examples#853]
### Describe the bug

EC2 key creation is now supported, but the EC2-instance example has removed it https://github.com/aws-samples/aws-cdk-examples/blob/d48d5319702d901fa9a0571aa4fc4d812fceb3d7/typescript/ec2-instance/lib/ec2-cdk-stack.ts#L14

### Expected Behavior

The EC2 example should allow key creation

### Current Behavior

The key creation has been removed from EC2 example

### Reproduction Steps

https://github.com/aws-samples/aws-cdk-examples/blob/d48d5319702d901fa9a0571aa4fc4d812fceb3d7/typescript/ec2-instance/lib/ec2-cdk-stack.ts#L14

### CDK CLI Version

2.80.0

### Node.js Version

v18.16.0

### OS

Mac OS Monterey 12.6.5

### Language

Typescript

**Comment by kaizio** [comment]
Merged
