### ISSUE TITLE
feat: StateMachineProps#definition is deprecated.

### ISSUE THREAD

**Issue by MichaelWalker-git** [aws-samples/aws-cdk-examples#868]
### Description
- Sample application is still using the deprecated definition approach. Can we refresh this sample-app to use definitionBody: DefinitionBody.fromChainable()?

https://github.com/aws-samples/aws-cdk-examples/blob/master/python/stepfunctions/stepfunctions/stepfunctions_stack.py

### Use Case

All future  CDK Stepfunction approaches

### Proposed Solution

definitionBody: DefinitionBody.fromChainable()

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### Language

Python

**Comment by mmarinm** [comment]
I'll submit PR for this issue
