### ISSUE TITLE
Quicksight automation with CDK - I did it and want to contribute it to the examples

### ISSUE THREAD

**Issue by gmournos** [aws-samples/aws-cdk-examples#870]
### Describe the feature

Hi,

I wrote an article to help the community to automate Quicksight assets generation (https://medium.com/@gmournos/aws-quicksight-as-code-a-unified-approach-for-quicksight-development-and-deployment-using-aws-30bbb6bd253a) and created a public repo (https://github.com/gmournos/quicksight-as-code) that automates the generation of the AWS samples provided by Quicksight.

I would like to contribute it here...

### Use Case

Deploying Quicksight with CDK is a much better approach than the ones proposed by AWS, using cross account templates. For a full list of benefits, look at section 1.1. of my article (https://medium.com/@gmournos/aws-quicksight-as-code-a-unified-approach-for-quicksight-development-and-deployment-using-aws-30bbb6bd253a) 

### Proposed Solution

I already implemented everything in https://github.com/gmournos/quicksight-as-code, I just want to contribute it here.

The solution is a unified approach, containing L2 constructs, CLI scripts, utilities etc as described in my article  (https://medium.com/@gmournos/aws-quicksight-as-code-a-unified-approach-for-quicksight-development-and-deployment-using-aws-30bbb6bd253a) 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Language

Typescript

**Comment by ericzbeard** [comment]
Looks great, let's do it. I've done a bit of QuickSight development and automation/repeatability has been a struggle. One request I have is to add as many code comments as you can - we want this repo to be a good data source for generative AI tools and it helps to have descriptive comments above code blocks.

**Comment by sebs** [comment]
i guess we begin to sit on a example of quicksight/cdk code as well. Different usecase. We could provide a very basic example as well. If that is something that is in need.

**Comment by gmournos** [comment]
Actually, I have a full framework for this. Forgot to contribute it, but I have some time this weekend, so I will comment it and contribute it.

**Comment by gmournos** [comment]
And here is the PR [https://github.com/aws-samples/aws-cdk-examples/pull/1059].
Sorry for taking so long to contribute this. I forgot about it and thought I did it last year. 

Happy reviewing

**Comment by sebs** [comment]
We are cooking a 'easy' example as well and maybe that more complex onw from @gmournos  makes sense with it as context. We stuck to the basics and it should be as briefly as it can get. 


https://github.com/MaibornWolff/aws-cdk-examples/tree/ts-quicksight-example
