### ISSUE TITLE
Argument of type 'Function' is not assignable to parameter of type 'IFunction'.

### ISSUE THREAD

**Issue by paritosh16** [aws-samples/aws-cdk-examples#89]
OS: macOS 10.14.6
aws-cdk/core: 1.0.0
aws-cdk/aws-lambda: 1.0.0
aws-cdk/aws-events: 1.1.0
aws-cdk/aws-events-targets: 1.1.0
cdk: 1.0.0 (build d89592e)

I am trying to create a stack similar to the [lambda-cron](https://github.com/aws-samples/aws-cdk-examples/blob/master/typescript/lambda-cron/index.ts) example. 

While adding lambda function to rule, it is erring out. 

Add a lambda function as a target: 
`rule.addTarget(new targets.LambdaFunction(queueConsumer));`

`queueConsumer` is a lambda function (`aws-cdk/aws-lambda.Function`) that consumes messages from a SQS queue. 

Error while adding the target
`Argument of type 'Function' is not assignable to parameter of type 'IFunction'.`

Is there any way to get the IFunction object from the lambda.Function object?

**Comment by rhboyd** [comment]
This is a hack that'll make it work, but I would open an Issue on the CDK repo for this. To get you unstuck, you can probably use the from­Function­Arn(functionArn=queueConsumer. functionArn()) method to swap out a real Function for an IFunction. 

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html#static-from-function-arnscope-id-functionarn

**Comment by rhboyd** [comment]
it's odd. LambdaFunction implements IFunction, so your code should work the way it is.

https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html

**Comment by paritosh16** [comment]
Absolutely! It should work the way it is but for some reason it isn't. It isn't working with the hack also. The error with the hack is:

```
Argument of type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-lambda/lib/function-base").IFunction' is not assignable to parameter of type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-secretsmanager/node_modules/@aws-cdk/aws-lambda/lib/function-base").IFunction'.
  Types of property 'role' are incompatible.
    Type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined' is not assignable to type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined'.
      Type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/role").IRole' is not assignable to type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/role").IRole'.
        Types of property 'grant' are incompatible.
          Type '(grantee: import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal, ...actions: string[]) => import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/grant").Grant' is not assignable to type '(grantee: import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal, ...actions: string[]) => import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/grant").Grant'.
            Types of parameters 'grantee' and 'grantee' are incompatible.
              Type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal' is not assignable to type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/principals").IPrincipal'.
                Types of property 'addToPolicy' are incompatible.
                  Type '(statement: import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean' is not assignable to type '(statement: import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement) => boolean'.
                    Types of parameters 'statement' and 'statement' are incompatible.
                      Type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement' is not assignable to type 'import("/Users/paritosw/cdk-test/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/policy-statement").PolicyStatement'.
```

I am totally stuck here. I'll open an issue on the CDK repo.

**Comment by rhboyd** [comment]
This seems odd, should they be nested that way?
`cdk-test/node_modules/@aws-cdk/aws-secretsmanager/node_modules/@aws-cdk/aws-lambda/lib/function-base`

**Comment by AtomicCactus** [comment]
A somewhat dirty workaround that worked for me:

```
const eventTargets = require("@aws-cdk/aws-events-targets");

const theFunction = new Function(this, ...);

new Rule(this, "Schedule", {
      enabled: true,
      schedule: Schedule.rate(Duration.minutes(15)),
      targets: [new eventTargets.LambdaFunction(theFunction)],
});
```

Basically using `require` instead of `import` solved the problem

**Comment by reidca** [comment]
Any resolution to this issue? I am attempting to create a custom resource which is asking for an IFunction. It seems neither Function nor SingletonFunction are accepted even though they both implement IFunction. I am left feeling this is a bug however there is very little information on this which I am surprised at.

**Comment by rhboyd** [comment]
@reidca I just verified that this works.

```
from aws_cdk import (
    aws_lambda as lambda_,
    aws_cloudformation as cfn,
    core
)

class MyStack(core.Stack):

    def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        my_func = lambda_.Function(
            self,
            "MyCRFunction",
            code=lambda_.InlineCode("def main(event, context)\n\tprint(event)"),
            handler="index.main",
            runtime=lambda_.Runtime.PYTHON_3_7
        )

        cfn.CustomResource(
            self,
            "MyCustomResource",
            provider=cfn.CustomResourceProvider.lambda_(handler=my_func)
        )

```

**Comment by reidca** [comment]
> @reidca I just verified that this works.
> 
> ```
> from aws_cdk import (
>     aws_lambda as lambda_,
>     aws_cloudformation as cfn,
>     core
> )
> 
> class MyStack(core.Stack):
> 
>     def __init__(self, scope: core.Construct, id: str, **kwargs) -> None:
>         super().__init__(scope, id, **kwargs)
> 
>         my_func = lambda_.Function(
>             self,
>             "MyCRFunction",
>             code=lambda_.InlineCode("def main(event, context)\n\tprint(event)"),
>             handler="index.main",
>             runtime=lambda_.Runtime.PYTHON_3_7
>         )
> 
>         cfn.CustomResource(
>             self,
>             "MyCustomResource",
>             provider=cfn.CustomResourceProvider.lambda_(handler=my_func)
>         )
> ```

Alas I need this to work in TypeScript although I prefer Python! The issue seems to be TypeScript specific.

**Comment by rhboyd** [comment]
Can you share your code that is producing the error? I would be very surprised if this worked in Python but not TS, it's usually the other way around if there's a bug.

**Comment by rhboyd** [comment]
I just verified that it works in TS as well. without seeing either your code or the error message you're getting, there's not much anyone can do to help.

**Comment by reidca** [comment]
> Can you share your code that is producing the error? I would be very surprised if this worked in Python but not TS, it's usually the other way around if there's a bug.

One of the reasons we chose TypeScript was to limit issues with the code being interpreted to Python from TypeScript, plus it seemed the documentation was more up to date for TypeScript.

The issue I am seeing can be seen when you try this sample:
[Custom-Resource](https://github.com/aws-samples/aws-cdk-examples/tree/master/typescript/custom-resource
)
I raised an issue for it as well: [Issue](https://github.com/aws-samples/aws-cdk-examples/issues/135
)
I am wanting to use a custom resource to work around the fact that you cannot setup notifications to invoke a lambda function for an existing S3 bucket. This is pretty much my first foray into proper use of CDK and it may not be the simplest example to have chosen as there does not seem to be any documentation on Custom Resources other than that sample I referenced earlier.

Any help appreciated!

**Comment by reidca** [comment]
> I just verified that it works in TS as well. without seeing either your code or the error message you're getting, there's not much anyone can do to help.

Can you send me the code you tried and also what version of CDK you are using? Perhaps we are using different versions or something else in my environment is wrong.

**Comment by rhboyd** [comment]
What error are you getting when you say "The supplied example for custom-resource is no longer compiling"? I just copied it verbatim into a CDK Construct and it synth'd without a problem.

**Comment by rhboyd** [comment]
I am using 1.10.1

**Comment by rhboyd** [comment]
I'm using the code from the example. I didn't use the `fs` library to load the code but that shouldn't make a difference.
```
import lambda = require('@aws-cdk/aws-lambda');
import cfn = require('@aws-cdk/aws-cloudformation');
import cdk = require('@aws-cdk/core');

export class CdkExampelsI89Stack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const resource = new cfn.CustomResource(this, 'Resource', {
      provider: cfn.CustomResourceProvider.lambda(new lambda.SingletonFunction(this, 'Singleton', {
        uuid: 'f7d4f730-4ee1-11e8-9c2d-fa7ae01bbebc',
        code: new lambda.InlineCode("def main(event, context)\n\tprint(event)"),
        handler: 'index.main',
        timeout: cdk.Duration.seconds(300),
        runtime: lambda.Runtime.PYTHON_3_7,
      })),
      properties: props
    });
  }
}
```

**Comment by reidca** [comment]
Odd...I get this design time error in VSCode:

Argument of type 'SingletonFunction' is not assignable to parameter of type 'IFunction'.
  Types of property 'role' are incompatible.
    Type 'import("c:/source/aws/cloudformation/cdk/s3-ftp-uploader/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined' is not assignable to type 'import("c:/source/aws/cloudformation/cdk/s3-ftp-uploader/node_modules/@aws-cdk/aws-cloudformation/node_modules/@aws-cdk/aws-iam/lib/role").IRole | undefined'.
      Type 'import("c:/source/aws/cloudformation/cdk/s3-ftp-uploader/node_modules/@aws-cdk/aws-iam/lib/role").IRole' is not assignable to type 'import("c:/source/aws/cloudformation/cdk/s3-ftp-uploader/node_modules/@aws-cdk/aws-cloudformation/node_modules/@aws-cdk/aws-iam/lib/role").IRole'.ts(2345)

Sounds like I am doing something wrong of have my env setup wrong.

**Comment by rhboyd** [comment]
what version of cdk are you using?

**Comment by reidca** [comment]
> what version of cdk are you using?

Same as you 1.10.1 (build 82f8ec6)

**Comment by rhboyd** [comment]
from your error message, it looks like a problem with the way you are defining a Role.

**Comment by rhboyd** [comment]
sharing your code would make this 100x easier instead of using a 20-questions approach

**Comment by reidca** [comment]
> from your error message, it looks like a problem with the way you are defining a Role.

Like you I have copied the code verbatim, I have not done anything with a role! The code is exactly as in the sample.

**Comment by rhboyd** [comment]
I would delete the node_modules folder and re-run `npm install` then try again. You probably have an old version of one of the CDK dependencies lurking in there

**Comment by reidca** [comment]
Found the issue! I had this installed:
https://www.npmjs.com/package/@aws-cdk/custom-resources

Looks like this is an old module and it has been superseded and incorporated into CDK CloudFormation module.

I wonder whether we can get this removed as was referenced from some site I found on CDK custom resources. 

Thank you so much for your help.

**Comment by rhboyd** [comment]
there are probably people still using that module, simply removing it would break their builds (see also leftpad)

**Comment by rhboyd** [comment]
looking at that module, it looks like it's part of CDK and is being actively developed. you may have had an old version of that module.

**Comment by reidca** [comment]
> there are probably people still using that module, simply removing it would break their builds (see also leftpad)

I guess so but perhaps a note to say that it's now part of a different module would help. As someone new to CDK and looking how to use Custom Resources this was definitely an unwanted distraction and has lost me lots of time.

**Comment by reidca** [comment]
> looking at that module, it looks like it's part of CDK and is being actively developed. you may have had an old version of that module.

I only downloaded it today!  

If you install it do you see the same issues I was having using the custom resource in CFN?

**Comment by rhboyd** [comment]
Running the following commands works as expected with no errors:

```
git clone https://github.com/aws-samples/aws-cdk-examples.git
cd aws-cdk-examples/typescript/custom-resource/
npm install
npm run build
cdk synth
```

**Comment by rhboyd** [comment]
you mentioned in the other issue that you had to remove a line from your `package.json` that wasn't part of the original example. The example works correctly on the current version of CDK.

**Comment by reidca** [comment]
I was trying to create a cdk app that used a custom resource and came across the npm module that I subsequently had to remove. Couldn't get this working so looked to samples. Found the sample mentioned and came across the errors I listed with Function not being compatible with IFunction. After our dialogue I then removed the entry from the package.json in the root of my project and did an npm install. This seems to have resolved the issue.

 I confess to being quite confused as to what the issue was and what the use of that npm module is. 

Is there a compatibility issue or is this something I have done wrong?

**Comment by rhboyd** [comment]
like I said, without seeing your code I have no idea.

**Comment by gbooth27** [comment]
I also just ran into this issue. I instantiate a function then try to add and S3 event trigger with `s3_notifications.LambdaDestination(this.my_lambda)` where `this.my_lambda` is the function and it is telling me `Argument of type 'Function' is not assignable to parameter of type 'IFunction'.` which makes no sense since `Function` implements `IFunction`, as stated in your docs: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda.Function.html

**Comment by gbooth27** [comment]
I see this error when I try to build: `Types have separate declarations of a private property 'action'.` and `Argument of type 'Function' is not assignable to parameter of type 'IFunction'.
  Types of property 'role' are incompatible.`

**Comment by musacibik** [comment]
You may try updating your dependencies. Make sure that all modules under aws-cdk have same versions installed.

This configuration worked for me.

`{
  "dependencies": {
    "@aws-cdk/aws-events-targets": "^1.18.0",
    "@aws-cdk/aws-glue": "^1.18.0",
    "@aws-cdk/aws-kinesisfirehose": "^1.18.0",
    "@aws-cdk/aws-s3": "^1.18.0",
    "@aws-cdk/aws-sns": "^1.18.0",
    "@aws-cdk/aws-sns-subscriptions": "^1.18.0",
    "@aws-cdk/core": "^1.18.0"
  }
}
`

**Comment by NGL321** [comment]
Reviewing older issues, the above guidance about checking versioning of dependencies should resolve the separate declarations issue. Is anyone still struggling with this?

**Comment by mspertus** [comment]
"npm update" solved the issue for me.

**Comment by falnyr** [comment]
![](https://i.ibb.co/H7Vp36t/download.png)

**Comment by armando25723** [comment]
Always when installing something in version different than core version.

**Comment by aezazali1997** [comment]
my issue was caused due to some extra dependency. after removing the dependency, the code started working without issues
