### ISSUE TITLE
Static Site will incorrectly create a new Hosted Zone

### ISSUE THREAD

**Issue by rhboyd** [aws-samples/aws-cdk-examples#93]
Because the example relies on an ACM Cert already existing, this would imply that the Hosted Zone already exists. The TypeScript static-site example will create a new Hosted Zone and the DNS Resolution will fail because the the new HZ is not the authority for the domain.

https://github.com/aws-samples/aws-cdk-examples/blob/8eae959ec8e409ba6d861650dcfa4bae1bbee56e/typescript/static-site/static-site.ts#L69-L71

**Comment by jewelsjacobs** [comment]
You can replace this with a lookup. I'm not sure the best way to implement this in the example though.

```
// Import Route53 existing hosted zone
const importedZone = route53.HostedZone.fromLookup(this, 'HostedZoneFromLookup', {
  domainName: props.domain
})

// Output:
new cdk.CfnOutput(this, 'HostedZoneId', { value: importedZone.hostedZoneId, exportName: 'HostedZoneID' });
new cdk.CfnOutput(this, 'ZoneName', { value: importedZone.zoneName, exportName: 'ZoneName' });

// Input props:
const hostedZoneProps = {
  hostedZoneId: cdk.Fn.importValue("HostedZoneID"),
  zoneName: cdk.Fn.importValue("ZoneName")
};

const siteDomain = props.siteSubDomain + '.' + props.domainName;

 // Route53 alias record for the CloudFront distribution
const zone = new route53.HostedZone(this, 'MyHostedZone', hostedZoneProps);
new route53.ARecord(this, 'SiteAliasRecord', {
  recordName: siteDomain,
  target: route53.AddressRecordTarget.fromAlias(new targets.CloudFrontTarget(distribution)),
  zone
 });
```

**Comment by rhboyd** [comment]
When I added the Python example I ask the user to supply the Hosted Zone's information so we could do the lookup.
