### ISSUE TITLE
Guide to bootstrapping using CloudFormation Stacksets missing IAM permission boundary examples

### ISSUE THREAD

**Issue by khushail** [aws-samples/aws-cdk-examples#966]
### Describe the bug

The guide to bootstrapping an account using CloudFormation stack sets published on the AWS blog makes specific mention of adding an IAM permission boundary but this is not included in the post.

```
In this post, you’ll perform the following steps to deploy the AWS CDK bootstrap template:

Extract the AWS CDK bootstrap CloudFormation template from the AWS CDK CLI
Customize the bootstrap template by adding an IAM permission boundary
```
The post has no further reference to this.

Link - https://aws.amazon.com/blogs/mt/bootstrapping-multiple-aws-accounts-for-aws-cdk-using-cloudformation-stacksets/

### Expected Behavior

The blog post should have updated links with example

### Current Behavior

missing information

### Reproduction Steps

check the links

### CDK CLI Version

n/a

### Node.js Version

n/a

### OS

n/a

### Language

Typescript

**Comment by kaizio** [comment]
This is not the repo for reporting issues in the CDK docs nor AWS Blog posts.
