### ISSUE TITLE
These stacks aren't going to clean themselves

### ISSUE THREAD

**Issue by rhboyd** [aws-samples/aws-cdk-examples#99]
Example apps should include necessary parameters so that resources are properly cleaned up with with `cdk destroy`. For example, setting S3 RemovalPolicy.DESTROY on all example buckets.

This would be a good first issue for a contributor.

**Comment by hellnation** [comment]
The suggestion is that the standard for aws-sdk-examples should be that roundtripping an example through cdk deploy/destroy shouldn't leave anything in the account wherever possible, and if it does it should be mentioned in the example code comments.

You mentioned DynamoDB as being similarly affected. I will see if there's something similar that can be done for them.

**Comment by hellnation** [comment]
In testing, I note that the behaviour for DynamoDB is different - it will delete the Table even if there is data in it (whereas S3 will error if the Bucket is not empty). I have adjusted the comments next to the code accordingly.

**Comment by rhboyd** [comment]
#100 fixes this. closing.
